Repository wazuh/wazuh-qa, pull requests merged in 2020-12, with the labels that each got.

#970 Move test_timezone_changes to test_files folder.
  tests/integration/test_fim/test_files/test_timezone_changes/data/wazuh_timezone_conf.yaml
  tests/integration/test_fim/test_files/test_timezone_changes/test_timezone_changes.py
Labels: core/fim

#973 Change names of daemons in integration tests
  .github/ISSUE_TEMPLATE/test--mitre.md
  .github/ISSUE_TEMPLATE/test--ruleset.md
  ansible/wazuh-ansible/molecule/wazuh-agent/tests/test_agents.py
  deps/wazuh_testing/wazuh_testing/data/mitre_event.json
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/test_agentd/data/wazuh_enrollment_tests.yaml
  tests/integration/test_agentd/test_agentd_enrollment_params.py
  tests/integration/test_agentd/test_agentd_multi_server.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_check_rare_socket_responses.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_check_socket_responses.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_validate_linux_analysisd_alerts.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_validate_rare_analysisd_alerts.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_validate_win32_analysisd_alerts.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/test_validate_win32_analysisd_registry_alerts.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/yaml_generators/generate_linux_yaml.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/yaml_generators/generate_windows_yaml.py
  tests/integration/test_analysisd/test_error_messages/test_error_messages.py
  tests/integration/test_analysisd/test_event_messages/test_event_messages.py
  tests/integration/test_analysisd/test_integrity_messages/test_integrity_messages.py
  tests/integration/test_analysisd/test_scan_messages/test_scan_messages.py
  tests/integration/test_api/test_config/test_use_only_authd/test_use_only_authd.py
  tests/integration/test_authd/test_authd.py
  tests/integration/test_authd/test_authd_agents_ctx.py
  tests/integration/test_authd/test_authd_local.py
  tests/integration/test_authd/test_authd_name_ip_pass.py
  tests/integration/test_authd/test_authd_ssl_certs.py
  tests/integration/test_authd/test_authd_ssl_options.py
  tests/integration/test_authd/test_authd_worker.py
  tests/integration/test_fim/test_files/conftest.py
  tests/integration/test_fim/test_files/test_audit/data/ossec.conf
  tests/integration/test_fim/test_files/test_inotify/test_num_watches.py
  tests/integration/test_fim/test_files/test_inotify/test_remove_rename_folder.py
  tests/integration/test_fim/test_files/test_process_priority/test_process_priority.py
  tests/integration/test_fim/test_files/test_stats_integrity_sync/data/template_wazuh_conf.conf
  tests/integration/test_fim/test_files/test_stats_integrity_sync/test_FIM_performance.py
  tests/integration/test_fim/test_files/test_stats_integrity_sync/test_stats_integrity_sync.py
  tests/integration/test_fim/test_registry/conftest.py
  tests/integration/test_fim/test_registry/test_registry_basic_usage/test_basic_usage_registry_baseline_generation.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_disk_quota_default.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_file_size_default.py
  tests/integration/test_fim/test_synchronization/conftest.py
  tests/integration/test_rids/test_rids.py
  tests/system/README.md
  tests/system/provisioning/agentless_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/agentless_cluster/roles/worker-role/files/ossec.conf
  tests/system/provisioning/basic_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/basic_cluster/roles/worker-role/files/ossec.conf
  tests/system/provisioning/enrollment_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/enrollment_cluster/roles/worker-role/files/ossec.conf
Labels: pending core

#975 Remove agent-info clean from agents ctx test cases
  tests/integration/test_authd/test_authd_agents_ctx.py
Labels: bug

#962 Add system tests for cluster integrity synchronization.
  tests/system/README.md
  tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
Labels: cluster

#991 Relocating SCA tests to new legacy folder
  tests/legacy/test_sca/test_basic_usage/data/sca_commands_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_compare_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_condition_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_directories_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_files_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_negation_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_processes_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_repeated_global_ids_1.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_repeated_global_ids_2.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_repeated_local_ids.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_win_registry_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/set_linux_config_to_compliance.sh
Labels: enhancement

#992 Creating a documentation file for the SCA tests
  tests/legacy/test_sca/README.md
  tests/legacy/test_sca/test_basic_usage/data/sca_commands_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_compare_test_suite.yml
  tests/legacy/test_sca/test_basic_usage/data/sca_directories_test_suite.yml
Labels: enhancement

#993 Skip/xfail tests for deprecated or in development features.
  tests/integration/test_api/test_config/test_behind_proxy_server/test_behind_proxy_server.py
  tests/integration/test_cluster/test_key_polling/test_key_polling_master.py
  tests/integration/test_cluster/test_key_polling/test_key_polling_worker.py
  tests/system/test_cluster/test_agent_key_polling/test_agent_key_polling.py
Labels: cluster, system-tests

#964 Replaced wazuh tools
  .github/ISSUE_TEMPLATE/test--gcp.md
  .github/ISSUE_TEMPLATE/test--mitre.md
  .github/ISSUE_TEMPLATE/test--ruleset.md
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/README.md
  tests/integration/test_gcloud/README.md
Labels: pending core

#1001 Parametrize wpk version on WPK tests
  deps/wazuh_testing/wazuh_testing/data/keepalives.txt
  deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
  tests/integration/README.md
  tests/integration/conftest.py
  tests/integration/test_wpk/conftest.py
  tests/integration/test_wpk/test_wpk_agent.py
  tests/integration/test_wpk/test_wpk_manager.py
  tests/integration/test_wpk/test_wpk_manager_task_states.py
Labels: enhancement
