Repository wazuh/wazuh-qa, pull requests merged in 2020-04, with the labels that each got.

#613 FIM System test: Transfer agents status data to jenkins node
  tests/system/fim/common_tasks/complete_summarize.py
  tests/system/fim/common_tasks/complete_summarize.yml
  tests/system/fim/common_tasks/create_files.yml
  tests/system/fim/common_tasks/delete_files.yml
  tests/system/fim/common_tasks/generate_results.py
  tests/system/fim/common_tasks/json2md.py
  tests/system/fim/common_tasks/modify_files.yml
  tests/system/fim/common_tasks/prepare.yml
  tests/system/fim/common_tasks/save_agent_state.yml
  tests/system/fim/common_tasks/summarize_action.py
  tests/system/fim/common_tasks/summarize_action.yml
  tests/system/fim/common_tasks/verify_alerts.yml
  tests/system/fim/common_tasks/verify_alerts_elasticsearch.py
  tests/system/fim/common_tasks/verify_alerts_json.py
  tests/system/fim/scenarios/201_default_configuration_frequency/launch_test_scenario.yml
  tests/system/fim/scenarios/202_realtime_monitoring/launch_test_scenario.yml
  tests/system/fim/scenarios/203_whodata_frequency/actions/install_whodata.yml
  tests/system/fim/scenarios/203_whodata_frequency/launch_test_scenario.yml
  tests/system/fim/scenarios/204_whodata_linux_noaudit/config/agent_windows_ossec.conf
  tests/system/fim/scenarios/204_whodata_linux_noaudit/launch_test_scenario.yml
  tests/system/fim/scenarios/205_restrict_option/launch_test_scenario.yml
  tests/system/fim/scenarios/206_tag_option/launch_test_scenario.yml
  tests/system/fim/scenarios/207_report_changes_frequency/launch_test_scenario.yml
  tests/system/fim/scenarios/208_ignore_files/actions/create_ignored_files.yml
  tests/system/fim/scenarios/208_ignore_files/actions/delete_ignored_files.yml
  tests/system/fim/scenarios/208_ignore_files/actions/modify_ignored_files.yml
  tests/system/fim/scenarios/208_ignore_files/launch_test_scenario.yml
  tests/system/fim/scenarios/209_recursion_level/actions/create_missing_files.yml
  tests/system/fim/scenarios/209_recursion_level/actions/delete_missing_files.yml
  tests/system/fim/scenarios/209_recursion_level/actions/modify_missing_files.yml
  tests/system/fim/scenarios/209_recursion_level/launch_test_scenario.yml
  tests/system/fim/scenarios/210_scheduled_scan/launch_test_scenario.yml
  tests/system/fim/scenarios/212_realtime_scheduled_monitoring/launch_test_scenario.yml
  tests/system/fim/vars/main.yml
  tests/system/provisioning/agents_status/.gitkeep
  tests/system/provisioning/agents_status_transfer.yml
  tests/system/provisioning/clean_environment.yml
  tests/system/provisioning/pipeline_debug.yml
Labels: fim-system-tests

#635 Add test to check correct number of inotify watches
  deps/wazuh_testing/wazuh_testing/fim.py
  tests/integration/test_fim/test_inotify/data/wazuh_conf_num_watches.yaml
  tests/integration/test_fim/test_inotify/test_num_watches.py
Labels: automation

#644 Test if the full_log is displayed correctly when it is very long
  deps/wazuh_testing/wazuh_testing/analysis.py
  tests/integration/test_analysisd/test_all_syscheckd_configurations/data/syscheck_rare_events.yaml
Labels: enhancement
