Repository wazuh/wazuh-qa, pull requests merged in 2021-11, with the labels that each got.

#2161 Tests WPK - Fix failures related to Rollback on Windows.
  deps/wazuh_testing/wazuh_testing/tools/remoted_sim.py
Labels: status/in-progress

#2151 Force options tests implentation
  deps/wazuh_testing/wazuh_testing/authd.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/test_authd/conftest.py
  tests/integration/test_authd/data/authd_key_hash.yaml
  tests/integration/test_authd/data/test_authd_force_insert.yaml
  tests/integration/test_authd/data/wazuh_authd_configuration.yaml
  tests/integration/test_authd/force_options/data/template_configuration.yaml
  tests/integration/test_authd/force_options/data/test_cases/after_registration_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/disconnected_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/invalid_config/invalid_configs.yaml
  tests/integration/test_authd/force_options/data/test_cases/key_mismatch.yaml
  tests/integration/test_authd/force_options/data/test_cases/legacy_force_insert.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/after_registration_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/disconnected_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/enablement_force_options.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/key_mismatch.yaml
  tests/integration/test_authd/force_options/test_authd_force_options.py
  tests/integration/test_authd/force_options/test_authd_force_options_invalid_config.py
  tests/integration/test_authd/test_authd_agents_ctx.py
  tests/integration/test_authd/test_authd_force_insert.py
  tests/integration/test_authd/test_authd_key_hash.py
  tests/integration/test_authd/test_authd_ssl_certs.py
  tests/integration/test_authd/test_authd_use_source_ip.py
  tests/integration/test_authd/test_authd_valid_name_ip.py
  tests/integration/test_authd/test_remote_enrollment.py
Labels: feature/authd

#2171 Authd replacement configurations QA
  deps/wazuh_testing/wazuh_testing/authd.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/conftest.py
  tests/integration/test_authd/authd.py
  tests/integration/test_authd/conftest.py
  tests/integration/test_authd/data/authd_key_hash.yaml
  tests/integration/test_authd/data/enroll_messages.yaml
  tests/integration/test_authd/data/enroll_ssl_options_tests.yaml
  tests/integration/test_authd/data/local_enroll_messages.yaml
  tests/integration/test_authd/data/test_authd_force_insert.yaml
  tests/integration/test_authd/data/wazuh_authd_configuration.yaml
  tests/integration/test_authd/data/worker_messages.yaml
  tests/integration/test_authd/force_options/README.md
  tests/integration/test_authd/force_options/data/template_configuration.yaml
  tests/integration/test_authd/force_options/data/test_cases/invalid_config/invalid_configs.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/after_registration_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/disconnected_time.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/enablement_force_options.yaml
  tests/integration/test_authd/force_options/data/test_cases/valid_config/key_mismatch.yaml
  tests/integration/test_authd/force_options/test_authd_force_options.py
  tests/integration/test_authd/force_options/test_authd_force_options_invalid_config.py
  tests/integration/test_authd/test_authd.py
  tests/integration/test_authd/test_authd_agents_ctx.py
  tests/integration/test_authd/test_authd_force_insert.py
  tests/integration/test_authd/test_authd_key_hash.py
  tests/integration/test_authd/test_authd_local.py
  tests/integration/test_authd/test_authd_ssl_certs.py
  tests/integration/test_authd/test_authd_ssl_options.py
  tests/integration/test_authd/test_authd_use_password.py
  tests/integration/test_authd/test_authd_use_source_ip.py
  tests/integration/test_authd/test_authd_valid_name_ip.py
  tests/integration/test_authd/test_authd_worker.py
  tests/integration/test_authd/test_remote_enrollment.py
  tests/integration/test_wazuh_db/data/global/global_messages.yaml
Labels: feature/wazuh-db, feature/authd

#2160 Tests VD - Fix failures related to `mock_agent` scope
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_extra_tags_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_url_feeds.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_ignore_time.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_debian_inventory_debian_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_redhat_inventory_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_ubuntu_inventory_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_windows/test_cpe_indexing.py
Labels: status/in-progress

#2204 Add wpk_revision for windows tests and skip manager tests
  tests/integration/test_wpk/test_wpk_manager.py
  tests/integration/test_wpk/test_wpk_manager_task_states.py
Labels: type/fix

#2251 Add `check-files` tool to the wazuh-qa framework
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
Labels: subteam/qa-thunder

#2246 Add `test_system_check_files` test
  requirements.txt
  tests/check_files/conftest.py
  tests/check_files/test_check_files/test_system_check_files.py
Labels: subteam/qa-thunder

#2267 Add new `qa-ctl` module to run custom ansible tasks
  deps/wazuh_testing/wazuh_testing/data/qactl_conf_validator_schema.json
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/__init__.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/ansible_runner.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/qa_provisioning.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/run_tasks/__init__.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/run_tasks/qa_tasks_launcher.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/run_tests/qa_test_runner.py
  deps/wazuh_testing/wazuh_testing/scripts/qa_ctl.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
Labels: subteam/qa-thunder

#2222 Fix Logcollector test for Windows and Solaris
  deps/wazuh_testing/wazuh_testing/logcollector.py
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/conftest.py
  tests/integration/test_logcollector/conftest.py
  tests/integration/test_logcollector/test_age/data/wazuh_age.yaml
  tests/integration/test_logcollector/test_age/test_age_basic.py
  tests/integration/test_logcollector/test_age/test_age_datetime_changed.py
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution.py
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_freq.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_age.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_alias.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_command.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_exclude.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_frequency.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_location.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_log_format.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_only_future_events.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_out_format.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_target.py
  tests/integration/test_logcollector/test_location/test_location.py
  tests/integration/test_logcollector/test_location_custom_sockets/test_location_custom_sockets.py
  tests/integration/test_logcollector/test_log_format/test_log_format_values.py
  tests/integration/test_logcollector/test_macos/test_macos_file_status_basic.py
  tests/integration/test_logcollector/test_macos/test_macos_file_status_predicate.py
  tests/integration/test_logcollector/test_macos/test_macos_file_status_when_no_macos.py
  tests/integration/test_logcollector/test_macos/test_macos_format_query.py
  tests/integration/test_logcollector/test_macos/test_macos_log_process.py
  tests/integration/test_logcollector/test_macos/test_macos_multiline_values.py
  tests/integration/test_logcollector/test_only_future_events/test_only_future_events.py
  tests/integration/test_logcollector/test_options/test_options_state_interval.py
  tests/integration/test_logcollector/test_options/test_options_state_interval_no_file.py
  tests/integration/test_logcollector/test_reconnect_time/test_reconnect_time.py
Labels: team/qa, type/rework, subteam/qa-earthquake

#2281 Remove old check
  tests/system/test_cluster/test_agent_info_sync/test_agent_info_sync.py
Labels: team/framework, release/4.3.0
