Repository wazuh/wazuh-qa, pull requests merged in 2021-10, with the labels that each got.

#1853 Enable WPK tests for macOS agents
  deps/wazuh_testing/wazuh_testing/data/keepalives.txt
  deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
  tests/integration/test_wpk/test_wpk_agent.py
  tests/integration/test_wpk/test_wpk_manager.py
Labels: test/upgrade, feature/wpk

#1954 Fix test_moving_files config yaml - disable modules
  tests/integration/test_fim/test_files/test_moving_files/data/wazuh_conf.yaml
Labels: feature/fim, type/fix

#1974 Add qa-branch parameter to the qa-ctl tool
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/qa_ctl_configuration.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/deployment/dockerfiles/qa_ctl/Dockerfile
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/local_actions.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/qa_provisioning.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/run_tests/qa_test_runner.py
  deps/wazuh_testing/wazuh_testing/scripts/qa_ctl.py
  deps/wazuh_testing/wazuh_testing/tools/github_repository.py
Labels: hacktoberfest-accepted

#1967 Modify windows yaml file and check recursion level on windows test
  tests/integration/test_fim/test_files/test_recursion_level/data/wazuh_recursion_windows.yaml
  tests/integration/test_fim/test_files/test_recursion_level/test_recursion_level.py
Labels: feature/fim, type/fix

#1953 Modify Report Changes config yaml to disable modules
  tests/integration/test_fim/test_files/test_report_changes/data/wazuh_conf.yaml
Labels: feature/fim, type/fix

#1976 Add skip parameters to the qa-ctl tool
  deps/wazuh_testing/wazuh_testing/qa_ctl/deployment/dockerfiles/qa_ctl/Dockerfile
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/local_actions.py
  deps/wazuh_testing/wazuh_testing/scripts/qa_ctl.py
Labels: hacktoberfest-accepted

#1987 Disable test_benchmark folder
  requirements.txt
  tests/integration/test_fim/test_files/test_benchmark/data/wazuh_conf.yaml
  tests/integration/test_fim/test_files/test_benchmark/test_benchmark.py
  tests/integration/test_fim/test_files/test_benchmark/test_report_changes_big.py
  tests/integration/test_fim/test_files/test_windows_audit_interval/data/wazuh_conf.yaml
Labels: feature/fim, type/fix

#2028 Add no-validation flag to the qa-ctl docker run for Windows
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/local_actions.py
Labels: hacktoberfest-accepted

#2036 Fix `qa-ctl` configuration path separators
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/qa_provisioning.py
Labels: hacktoberfest-accepted

#2061 Migrate `test_registry_ambiguous_confs` of `test_fim/test_registry` documentation to `qa-docs`
  docs/DocGenerator/config.yaml
  tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_complex.py
  tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_duplicated_entries.py
  tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_ignore_works_over_restrict.py
  tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_simple.py
Labels: hacktoberfest-accepted

#2074 Improve `qa-docs` errors checking
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
  deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/code_parser.py
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  deps/wazuh_testing/wazuh_testing/scripts/qa_docs.py
  tests/integration/test_active_response/test_execd/test_execd_firewall_drop.py
  tests/integration/test_active_response/test_execd/test_execd_restart.py
  tests/integration/test_api/test_config/test_cache/test_cache.py
  tests/integration/test_api/test_config/test_cors/test_cors.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_enabled.py
Labels: hacktoberfest-accepted

#2054 Fix `test_logtest/test_remove_old_sessions/`: autoconfigure local internal options
  tests/integration/test_logtest/test_remove_old_sessions/test_remove_old_session_for_inactivity.py
  tests/integration/test_logtest/test_remove_old_sessions/test_remove_old_sessions.py
Labels: hacktoberfest-accepted
