Repository wazuh/wazuh-qa, pull requests merged in 2021-12, with the labels that each got.

#2292 Add new check files fields
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
  tests/check_files/test_check_files/test_system_check_files.py
Labels: subteam/qa-thunder

#2289 Remove expected `force` option from the received request in the `agent_enrollment` system tests
  tests/system/test_cluster/test_agent_enrollment/data/messages.yml
Labels: team/framework, feature/cluster, feature/api

#2371 Add check file system integrity test and framework
  deps/wazuh_testing/wazuh_testing/data/qactl_conf_validator_schema.json
  deps/wazuh_testing/wazuh_testing/qa_ctl/VERSION.json
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_instance.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/__init__.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/playbook_generator.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/s3_package.py
  deps/wazuh_testing/wazuh_testing/tools/time.py
  tests/check_file_system_integrity/conftest.py
  tests/check_file_system_integrity/launcher.py
  tests/check_file_system_integrity/test_check_file_system_integrity.py
Labels: subteam/qa-thunder

#2383 Add the new `test_check_file_system_integrity` logic
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/check_file_system_integrity/data/warning_list.txt
  tests/check_file_system_integrity/test_check_file_system_integrity.py
Labels: subteam/qa-thunder

#2339 Mark as solved framework vulnerabilities
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
  tests/scans/code_analysis/known_flaws/known_flaws_wodles.json
Labels: subteam/qa-hurricane

#2352 Fixed a flaw regarding pseudo random generators
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2361 Mark Framework flaws as false positive
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane
