Repository wazuh/wazuh-qa, pull requests merged in 2022-11, with the labels that each got.

#3538 Skip unstable integration test for agentd
  CHANGELOG.md
  tests/integration/test_agentd/test_agentd_multi_server.py
Labels: subteam/qa-main, pull-request/production

#3531 Skip xfailed integration tests for gcloud
  CHANGELOG.md
  tests/integration/test_gcloud/test_functionality/test_day_wday.py
Labels: pull-request/production

#3563 Update Authd IT `force_options` tests
  CHANGELOG.md
  tests/integration/test_authd/force_options/data/test_cases/valid_config/enablement_force_options.yaml
Labels: pull-request/production

#3562 Refactor `test_remove_audit` to retry package installation if busy
  CHANGELOG.md
  tests/integration/test_fim/test_files/test_audit/test_remove_audit.py
Labels: target/4.4.0, pull-request/production

#3564 Update EPS limits tests according to the new changes
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_missing_configuration.yaml
  tests/integration/test_analysisd/test_limit_eps/test_configuration.py
Labels: pull-request/production

#3473 Update dependencies scan test and known flaws of both code and dependencies vulnerabilities tests
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/scans/dependencies.py
  tests/scans/code_analysis/known_flaws/known_flaws_api.json
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
  tests/scans/code_analysis/known_flaws/known_flaws_wodles.json
  tests/scans/dependencies/known_flaws_deps.json
  tests/scans/dependencies/test_dependencies.py
Labels: pull-request/production

#3602 Fix unstable logcollector test_macos_format_query
  CHANGELOG.md
  tests/integration/test_logcollector/test_macos/test_macos_format_query.py
Labels: pull-request/production

#3623 Fix FIM tests for Solaris agent
  CHANGELOG.md
  tests/integration/test_fim/test_files/test_basic_usage/data/wazuh_conf_check_realtime.yaml
  tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py
Labels: pull-request/production

#3609 Add test to check if syslog message are parsed correctly in the `alerts.json` file
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/scripts/syslog_simulator.py
  deps/wazuh_testing/wazuh_testing/tools/run_simulator.py
  tests/integration/test_remoted/test_socket_communication/data/configuration_template/configuration_syslog_message_parser.yaml
  tests/integration/test_remoted/test_socket_communication/data/test_cases/cases_syslog_message_parser.yaml
  tests/integration/test_remoted/test_socket_communication/test_syslog_message_parser.py
Labels: pull-request/production

#3380 FIM IT: add fim sync overlap testing
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/fim/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/fim/event_monitor.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  tests/integration/conftest.py
  tests/integration/test_fim/conftest.py
  tests/integration/test_fim/test_synchronization/data/configuration_template/configuration_sync_overlap.yaml
  tests/integration/test_fim/test_synchronization/data/configuration_template/configuration_sync_time.yaml
  tests/integration/test_fim/test_synchronization/data/test_cases/cases_sync_overlap.yaml
  tests/integration/test_fim/test_synchronization/data/test_cases/cases_sync_time.yaml
  tests/integration/test_fim/test_synchronization/test_sync_overlap.py
  tests/integration/test_fim/test_synchronization/test_sync_time.py
Labels: pull-request/development
