Repository wazuh/wazuh-qa, pull requests merged in 2022-09, with the labels that each got.

#3229 E2E tests: Disable AWS test
  tests/end_to_end/test_basic_cases/test_aws_infrastructure_monitoring/test_aws_infrastructure_monitoring.py
Labels: team/qa, subteam/qa-hurricane

#3235 E2E tests: Fix Brute Force tests
  tests/end_to_end/data/ansible_roles/manage_alerts/tasks/search_alert.yaml
  tests/end_to_end/data/env_requirements.json
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_rdp/data/playbooks/configuration.yaml
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_rdp/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_rdp/data/test_cases/cases_brute_force_rdp.yaml
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_ssh/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_ssh/data/test_cases/cases_brute_force_ssh.yaml
Labels: team/qa, subteam/qa-hurricane

#3236 E2E tests: Fix osquery test
  tests/end_to_end/test_basic_cases/test_osquery_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_osquery_integration/data/test_cases/cases_osquery_integration.yaml
Labels: team/qa, subteam/qa-hurricane

#3243 E2E tests: Fix Emotet test
  tests/end_to_end/pytest.ini
  tests/end_to_end/test_basic_cases/test_emotet/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_emotet/data/test_cases/cases_emotet.yaml
Labels: team/qa, subteam/qa-hurricane

#2984 Add IT to verify Active Response works with overwritten rules
  .github/workflows/scripts/linter.py
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/processes/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/integration/conftest.py
  tests/integration/test_active_response/test_analysisd/data/configuration_template/configuration_overwritten_rules.yaml
  tests/integration/test_active_response/test_analysisd/data/rules/0270-web_appsec_rules_edit.xml
  tests/integration/test_active_response/test_analysisd/data/rules/local_rules.xml
  tests/integration/test_active_response/test_analysisd/data/scripts/custom-ar.sh
  tests/integration/test_active_response/test_analysisd/data/test_cases/cases_overwritten_rules.yaml
  tests/integration/test_active_response/test_analysisd/test_overwritten_rules_ar.py
Labels: team/qa, subteam/qa-storm

#3250 E2E tests: Change inventory validation
  tests/end_to_end/conftest.py
Labels: team/qa, subteam/qa-hurricane

#3077 Add IT to verify Active Response works with overwritten rules - 4.4
  CHANGELOG.md
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/processes/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/conftest.py
  tests/integration/test_active_response/test_analysisd/data/configuration_template/configuration_overwritten_rules.yaml
  tests/integration/test_active_response/test_analysisd/data/rules/0270-web_appsec_rules_edit.xml
  tests/integration/test_active_response/test_analysisd/data/rules/local_rules.xml
  tests/integration/test_active_response/test_analysisd/data/scripts/custom-ar.sh
  tests/integration/test_active_response/test_analysisd/data/test_cases/cases_overwritten_rules.yaml
  tests/integration/test_active_response/test_analysisd/test_overwritten_rules_ar.py
Labels: team/qa, subteam/qa-storm

#3198 Add `v` to agent version in `simulate_agents`
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/scripts/simulate_agents.py
Labels: type/enhancement, tool/agent-simulator, qa-revision

#3263 Logcollector IT: Skip flaky tests
  CHANGELOG.md
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_dbg.py
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_freq.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_age.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_only_future_events.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_query.py
Labels: team/qa, test/integration, feature/logcollector, subteam/qa-rainbow

#3299 Test Integration - fix vulnerability validate feed content test
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
Labels: target/4.4.0, pull-request/production

#3314 Fix Windows framework installation error for python3.10
  CHANGELOG.md
  requirements.txt
Labels: pull-request/production

#3315 Fix Windows framework installation error for python3.10 - 4.4
  CHANGELOG.md
  requirements.txt
Labels: pull-request/production

#3157 Enhancement - Fix test scan commit option
  CHANGELOG.md
  tests/scans/code_analysis/conftest.py
Labels: pull-request/production

#3379 Fix Authd IT force_options tests
  CHANGELOG.md
  tests/integration/test_authd/force_options/data/test_cases/valid_config/enablement_force_options.yaml
Labels: pull-request/development

#3397 Revert PR #3379 "Fix Authd IT force_options tests"
  CHANGELOG.md
  tests/integration/test_authd/force_options/data/test_cases/valid_config/enablement_force_options.yaml
Labels: pull-request/production
