Repository wazuh/wazuh-qa, pull requests merged in 2022-08, with the labels that each got.

#3137 E2E Test: New test case added to test Wazuh when an RDP brute force attack is attempted
  tests/end_to_end/test_brute_force/data/playbooks/configuration.yaml
  tests/end_to_end/test_brute_force/data/playbooks/generate_events.yaml
  tests/end_to_end/test_brute_force/data/test_cases/cases_brute_force.yaml
  tests/end_to_end/test_brute_force/test_brute_force.py
Labels: team/qa, subteam/qa-hurricane

#3092 E2E test: AWS infrastructure monitoring
  tests/end_to_end/conftest.py
  tests/end_to_end/test_aws_infrastructure_monitoring/README.md
  tests/end_to_end/test_aws_infrastructure_monitoring/data/configuration/aws_cloudtrail_event.py
  tests/end_to_end/test_aws_infrastructure_monitoring/data/playbooks/configuration.yaml
  tests/end_to_end/test_aws_infrastructure_monitoring/data/playbooks/generate_events.yaml
  tests/end_to_end/test_aws_infrastructure_monitoring/data/playbooks/teardown.yaml
  tests/end_to_end/test_aws_infrastructure_monitoring/data/test_cases/cases_aws_infrastructure_monitoring.yaml
  tests/end_to_end/test_aws_infrastructure_monitoring/test_aws_infrastructure_monitoring.py
  tests/end_to_end/test_osquery_integration/test_osquery_integration.py
Labels: team/qa, subteam/qa-hurricane

#3140 IT Authd: Fix authd nightly fails - 4.4
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/services.py
Labels: feature/authd, type/fix, subteam/qa-storm

#3115 E2E Test: New module to test the integration with Yara
  deps/wazuh_testing/wazuh_testing/end_to_end/__init__.py
  tests/end_to_end/test_yara_integration/data/configuration/yara.sh
  tests/end_to_end/test_yara_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_yara_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_yara_integration/data/playbooks/teardown.yaml
  tests/end_to_end/test_yara_integration/data/test_cases/cases_yara_integration.yaml
  tests/end_to_end/test_yara_integration/test_yara_integration.py
Labels: team/qa, subteam/qa-hurricane

#3138 E2E Test: Windows Defender
  tests/end_to_end/test_windows_defender/data/playbooks/configuration.yaml
  tests/end_to_end/test_windows_defender/data/playbooks/generate_events.yaml
  tests/end_to_end/test_windows_defender/data/playbooks/teardown.yaml
  tests/end_to_end/test_windows_defender/data/test_cases/cases_windows_defender.yaml
  tests/end_to_end/test_windows_defender/test_windows_defender.py
Labels: team/qa, subteam/qa-hurricane

#3130 E2E test: New module to test the integration with Suricata
  tests/end_to_end/test_suricata_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_suricata_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_suricata_integration/data/playbooks/teardown.yaml
  tests/end_to_end/test_suricata_integration/data/test_cases/cases_suricata_integration.yaml
  tests/end_to_end/test_suricata_integration/test_suricata_integration.py
Labels: team/qa, subteam/qa-hurricane

#3129 E2E Test: Emotet
  tests/end_to_end/test_emotet/data/playbooks/configuration.yaml
  tests/end_to_end/test_emotet/data/playbooks/generate_events.yaml
  tests/end_to_end/test_emotet/data/playbooks/teardown.yaml
  tests/end_to_end/test_emotet/data/test_cases/cases_emotet.yaml
  tests/end_to_end/test_emotet/test_emotet.py
Labels: team/qa, subteam/qa-hurricane

#3141 E2E test: IP reputation and Active Response
  tests/end_to_end/test_ip_reputation/data/playbooks/configuration.yaml
  tests/end_to_end/test_ip_reputation/data/playbooks/generate_events.yaml
  tests/end_to_end/test_ip_reputation/data/playbooks/teardown.yaml
  tests/end_to_end/test_ip_reputation/data/test_cases/cases_ip_reputation.yaml
  tests/end_to_end/test_ip_reputation/test_ip_reputation.py
Labels: team/qa, subteam/qa-hurricane

#3136 E2E design and implementation: Slack integration
  tests/end_to_end/test_slack_integration/data/configuration/slack_api_script.py
  tests/end_to_end/test_slack_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_slack_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_slack_integration/data/playbooks/teardown.yaml
  tests/end_to_end/test_slack_integration/data/test_cases/cases_slack_integration.yaml
  tests/end_to_end/test_slack_integration/test_slack_integration.py
Labels: team/qa, subteam/qa-hurricane

#3174 E2E tests: Unify Virustotal tests
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/playbooks/teardown.yaml
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/test_cases/cases_virustotal.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/configuration.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/generate_events.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/test_cases/cases_virustotal.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/test_virustotal_fim.py
  tests/end_to_end/test_virustotal_integration/data/active_response_script/remove-threat.sh
  tests/end_to_end/test_virustotal_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_virustotal_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_virustotal_integration/data/playbooks/teardown.yaml
  tests/end_to_end/test_virustotal_integration/data/test_cases/cases_virustotal_integration.yaml
  tests/end_to_end/test_virustotal_integration/test_virustotal_integration.py
Labels: team/qa, subteam/qa-hurricane

#3172 IT VDT: Remove Debian Stretch Support
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/test_retry_interval.py
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
Labels: test/integration, feature/vuln-detector, type/fix, subteam/qa-storm

#3122 Enhancement - ProvisioningTool: Create provisioning templates for wazuh/qa roles
  provisioning/playbooks/wazuh_environment.yaml
  provisioning/roles.yaml
  provisioning/roles/apache/schema.j2
  provisioning/roles/createInventory.yaml
  provisioning/roles/qa_framework/schema.j2
  provisioning/roles/wazuh_environment/schema.j2
Labels: team/qa, subteam/qa-thunder

#3188 E2E tests: Change required environment for Suricata test
  tests/end_to_end/test_basic_cases/test_suricata_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_basic_cases/test_suricata_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_suricata_integration/data/playbooks/teardown.yaml
  tests/end_to_end/test_basic_cases/test_suricata_integration/test_suricata_integration.py
Labels: team/qa, subteam/qa-hurricane

#3180 Add new system test for `GET /cluster/ruleset/synchronization` endpoint
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/system.py
  tests/system/README.md
  tests/system/test_cluster/conftest.py
  tests/system/test_cluster/test_ruleset_sync_status/data/master_messages.yaml
  tests/system/test_cluster/test_ruleset_sync_status/data/worker_messages.yaml
  tests/system/test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py
Labels: type/feature, test/system, subteam/qa-hurricane, qa-revision

#3146 IT: Fix tests fails caused by stats socket changes
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/test_logtest/test_configuration/test_get_configuration_sock.py
  tests/integration/test_logtest/test_log_process_options/data/rules_verbose.yaml
  tests/integration/test_remoted/test_agent_communication/test_request_agent_info.py
  tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
  tests/integration/test_wazuh_db/test_wazuhdb_getconfig.py
Labels: test/integration, feature/wazuh-db, type/fix, subteam/qa-storm

#3175 E2E tests: Add an initial validation stage
  tests/end_to_end/README.md
  tests/end_to_end/conftest.py
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_controller_indexer.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_filebeat_indexer.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/main.yaml
  tests/end_to_end/data/ansible_roles/service_controller/tasks/get_installation_type.yaml
  tests/end_to_end/data/env_requirements.json
  tests/end_to_end/data/validation_playbooks/generate_general_play.yaml
  tests/end_to_end/data/validation_templates/general_validation.j2
  tests/end_to_end/test_basic_cases/test_fim/test_fim_windows/data/playbooks/configuration.yaml
Labels: team/qa, subteam/qa-hurricane

#3214 E2E tests: Skip Vulnerability Detector Windows test
  tests/end_to_end/test_basic_cases/test_vulnerability_detector/test_vulnerability_detector_windows/test_vulnerability_detection_windows.py
Labels: team/qa, subteam/qa-hurricane

#3216 E2E: Add markers linux and windows
  tests/end_to_end/test_basic_cases/test_audit/test_audit.py
  tests/end_to_end/test_basic_cases/test_aws_infrastructure_monitoring/test_aws_infrastructure_monitoring.py
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_rdp/test_brute_force_rdp.py
  tests/end_to_end/test_basic_cases/test_brute_force/test_brute_force_ssh/test_brute_force_ssh.py
  tests/end_to_end/test_basic_cases/test_detecting_suspicious_binaries/test_detecting_suspicious_binaries.py
  tests/end_to_end/test_basic_cases/test_docker_monitoring/test_docker_monitoring.py
  tests/end_to_end/test_basic_cases/test_emotet/test_emotet.py
  tests/end_to_end/test_basic_cases/test_fim/test_fim_linux/test_fim_linux.py
  tests/end_to_end/test_basic_cases/test_fim/test_fim_windows/test_fim_windows.py
  tests/end_to_end/test_basic_cases/test_ip_reputation/test_ip_reputation.py
  tests/end_to_end/test_basic_cases/test_osquery_integration/test_osquery_integration.py
  tests/end_to_end/test_basic_cases/test_shellshock_attack_detection/test_shellshock_attack_detection.py
  tests/end_to_end/test_basic_cases/test_slack_integration/test_slack_integration.py
  tests/end_to_end/test_basic_cases/test_sql_injection/test_sql_injection.py
  tests/end_to_end/test_basic_cases/test_suricata_integration/test_suricata_integration.py
  tests/end_to_end/test_basic_cases/test_unauthorized_processes_detection/test_unauthorized_processes_detection.py
  tests/end_to_end/test_basic_cases/test_virustotal_integration/test_virustotal_integration.py
  tests/end_to_end/test_basic_cases/test_vulnerability_detector/test_vulnerability_detector_linux/test_vulnerability_detector_linux.py
  tests/end_to_end/test_basic_cases/test_vulnerability_detector/test_vulnerability_detector_windows/test_vulnerability_detection_windows.py
  tests/end_to_end/test_basic_cases/test_windows_defender/test_windows_defender.py
  tests/end_to_end/test_basic_cases/test_yara_integration/test_yara_integration.py
Labels: team/qa, subteam/qa-hurricane

#3215 E2E tests: Improve validation stage
  tests/end_to_end/README.md
  tests/end_to_end/conftest.py
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_connection.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_controller_indexer.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
  tests/end_to_end/data/ansible_roles/host_checker/tasks/main.yaml
  tests/end_to_end/data/ansible_roles/service_controller/tasks/get_installation_type.yaml
  tests/end_to_end/data/env_requirements.json
  tests/end_to_end/data/validation_templates/general_validation.j2
Labels: team/qa, subteam/qa-hurricane
