Repository wazuh/wazuh-qa, pull requests merged in 2022-12, with the labels that each got.

#3641 Update logcollector format test due to audit changes
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/logcollector.py
Labels: team/qa, pull-request/production

#3614 Include Fragmentation information to getconfig endpoint wazuhdb IT case
  CHANGELOG.md
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
Labels: target/4.4.0, pull-request/production

#3660 Fix Yara and Virustotal E2E tests
  CHANGELOG.md
  tests/end_to_end/test_basic_cases/test_virustotal_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_basic_cases/test_yara_integration/data/playbooks/configuration.yaml
Labels: team/qa, qa-internal, subteam/qa-main, pull-request/production

#3689 Fix error in requirements.txt
  CHANGELOG.md
  requirements.txt
Labels: pull-request/production

#3700 Add manager statistics format test
  tests/integration/test_api/test_statistics/data/configuration_template/configuration_statistics_format.yaml
  tests/integration/test_api/test_statistics/data/configuration_template/wazuh-analysisd_template.json
  tests/integration/test_api/test_statistics/data/configuration_template/wazuh-db_template.json
  tests/integration/test_api/test_statistics/data/configuration_template/wazuh-remoted_template.json
  tests/integration/test_api/test_statistics/data/test_cases/cases_statistics_format.yaml
  tests/integration/test_api/test_statistics/test_statistics_format.py
Labels: team/qa, subteam/qa-main, pull-request/development
