Repository wazuh/wazuh-qa, pull requests merged in 2022-06, with the labels that each got.

#2635 API - Test the format of the logs (JSON logs support)
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/api.py
  deps/wazuh_testing/wazuh_testing/modules/api/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/api/event_monitor.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/test_api/conftest.py
  tests/integration/test_api/test_config/test_host_port/test_host_port.py
  tests/integration/test_api/test_config/test_logs/data/configuration_template/configuration_api_logs_format.yaml
  tests/integration/test_api/test_config/test_logs/data/test_cases/cases_api_logs_formats.yaml
  tests/integration/test_api/test_config/test_logs/test_api_logs_formats.py
  tests/integration/test_api/test_config/test_logs/test_logs.py
  tests/integration/test_authd/conftest.py
Labels: team/qa, subteam/qa-hurricane

#2945 IT VDT - Add SUSE Linux Enterpise Support for 4.4
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml.bz2
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml.gz
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_missing_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_from_year.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_missing_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_multiple_provider_feeds.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_from_year.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_interval.py
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_no_agent_data.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: team/qa, test/integration, feature/vuln-detector, subteam/qa-storm

#2847 Vulnerability Detector integration tests for `SUSE Linux Enterprise`
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml.bz2
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml.gz
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_missing_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_from_year.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_missing_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_multiple_provider_feeds.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_from_year.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_interval.py
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_no_agent_data.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: team/qa, test/integration, feature/vuln-detector, subteam/qa-storm

#2917 Logcollector Tier 0: Failed test_basic_configuration_log_format - 4.5.0
  deps/wazuh_testing/wazuh_testing/logcollector.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_log_format.py
Labels: team/qa, test/integration, subteam/qa-storm

#2966 IT WDB: Remove deprecated commands
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
  tests/integration/test_wazuh_db/data/global/global_messages.yaml
Labels: team/qa, test/integration, feature/wazuh-db, subteam/qa-storm

#2977 IT FIM - Fix Solaris and Macos fails for 4.3
  deps/wazuh_testing/wazuh_testing/fim.py
  tests/integration/test_fim/test_files/test_basic_usage/data/wazuh_conf_check_realtime.yaml
  tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_change_target.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_delete_symlink.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_monitor_symlink.py
Labels: team/qa, test/integration, feature/fim, type/fix, subteam/qa-storm, target/4.3.4

#2976 IT FIM - Fix Solaris and Macos fails - For 4.4
  deps/wazuh_testing/wazuh_testing/fim.py
  tests/integration/test_fim/test_files/test_basic_usage/data/wazuh_conf_check_realtime.yaml
  tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_change_target.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_delete_symlink.py
  tests/integration/test_fim/test_files/test_follow_symbolic_link/test_monitor_symlink.py
Labels: team/qa, test/integration, feature/fim, type/fix, subteam/qa-storm, target/4.4.0

#2987 System tests: Automatic Provision - Custom playbooks creation
  provisioning/wazuh_ansible_playbooks/wazuh_environment.yaml
Labels: team/qa, subteam/qa-thunder

#3001 E2E test: Refactor audit test
  .github/workflows/scripts/linter.py
  deps/wazuh_testing/wazuh_testing/end_to_end/__init__.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_audit/data/test_cases/cases_audit.yaml
  tests/end_to_end/test_audit/test_audit.py
Labels: team/qa, subteam/qa-hurricane

#2938 E2E SSH Brute force attack
  tests/end_to_end/test_brute_force/data/playbooks/generate_events.yaml
  tests/end_to_end/test_brute_force/data/test_cases/cases_brute_force.yaml
  tests/end_to_end/test_brute_force/test_brute_force.py
Labels: team/qa, subteam/qa-hurricane

#2955 Vulnerability Detector integration tests for Amazon Linux 2022
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  tests/integration/test_vulnerability_detector/data/feeds/alas/custom_alas_2022_feed.json
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_interval.py
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: team/qa, test/integration, feature/vuln-detector, subteam/qa-storm

#3005 Update xfailed API workload tests list
  tests/performance/test_api/test_api_endpoints_performance.py
Labels: team/qa, subteam/qa-hurricane, qa-revision

#3011 E2E test: Netcat
  tests/end_to_end/test_netcat/data/playbooks/configuration.yaml
  tests/end_to_end/test_netcat/data/playbooks/generate_events.yaml
  tests/end_to_end/test_netcat/data/test_cases/cases_netcat.yaml
  tests/end_to_end/test_netcat/test_netcat.py
Labels: team/qa, subteam/qa-hurricane

#3025 E2E Test: SQL Injection
  tests/end_to_end/test_sql_injection/data/playbooks/configuration.yaml
  tests/end_to_end/test_sql_injection/data/playbooks/generate_events.yaml
  tests/end_to_end/test_sql_injection/data/test_cases/cases_sql_injection.yaml
  tests/end_to_end/test_sql_injection/test_sql_injection.py
Labels: team/qa, subteam/qa-hurricane

#3006 Fix GCloud IT: test_max_messages error
  deps/wazuh_testing/wazuh_testing/gcloud.py
  tests/integration/test_gcloud/test_functionality/test_max_messages.py
Labels: team/qa, subteam/qa-storm

#3012 E2E test development: Osquery
  tests/end_to_end/conftest.py
  tests/end_to_end/test_osquery_integration/data/configuration/osquery_integration.json
  tests/end_to_end/test_osquery_integration/data/playbooks/configuration.yaml
  tests/end_to_end/test_osquery_integration/data/playbooks/generate_events.yaml
  tests/end_to_end/test_osquery_integration/data/test_cases/cases_osquery_integration.yaml
  tests/end_to_end/test_osquery_integration/test_osquery_integration.py
Labels: team/qa, subteam/qa-hurricane

#2921 Fix syscollector deltas IT
  .github/workflows/scripts/config/yaml_linter_config.yaml
  tests/integration/test_analysisd/test_syscollector/data/syscollector.yaml
  tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
  tests/integration/test_wazuh_db/data/agent/syscollector_deltas_messages.yaml
Labels: team/qa, subteam/qa-storm, feature/syscollector, target/4.4.0

#3028 E2E test: Test the detection of a Shellshock attack
  tests/end_to_end/test_shellshock_attack_detection/data/playbooks/configuration.yaml
  tests/end_to_end/test_shellshock_attack_detection/data/playbooks/generate_events.yaml
  tests/end_to_end/test_shellshock_attack_detection/data/test_cases/cases_shellshock_attack_detection.yaml
  tests/end_to_end/test_shellshock_attack_detection/test_shellshock_attack_detection.py
Labels: team/qa, subteam/qa-hurricane

#2948 E2E test: Monitoring Docker
  deps/wazuh_testing/wazuh_testing/end_to_end/__init__.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_docker_monitoring/data/playbooks/configuration.yaml
  tests/end_to_end/test_docker_monitoring/data/playbooks/generate_events.yaml
  tests/end_to_end/test_docker_monitoring/data/test_cases/cases_docker_monitoring.yaml
  tests/end_to_end/test_docker_monitoring/test_docker_monitoring.py
Labels: team/qa, subteam/qa-hurricane
