Repository wazuh/wazuh-qa, pull requests merged in 2022-10, with the labels that each got.

#3365 Add a test to check the analysisd socket properties
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/test_analysisd/conftest.py
  tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py
Labels: pull-request/production

#3413 Add new `analysisd` test suite: `test_limit_eps`
  CHANGELOG.md
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/data/all_disabled_ossec.conf
  deps/wazuh_testing/wazuh_testing/modules/analysisd/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  deps/wazuh_testing/wazuh_testing/scripts/simulate_agents.py
  deps/wazuh_testing/wazuh_testing/scripts/syslog_simulator.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/run_simulator.py
  requirements.txt
  tests/integration/conftest.py
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/basic_test_module/configuration_disabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/basic_test_module/configuration_enabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_accepted_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_invalid_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_missing_configuration.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_drop_events_when_queue_is_full.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_processing_events_in_order_multi_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_processing_events_in_order_single_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_queueing_events_after_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/basic_test_module/cases_disabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/basic_test_module/cases_enabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_accepted_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_invalid_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_missing_configuration.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_drop_events_when_queue_is_full.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_processing_events_in_order_multi_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_processing_events_in_order_single_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_queueing_events_after_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/test_basic.py
  tests/integration/test_analysisd/test_limit_eps/test_configuration.py
  tests/integration/test_analysisd/test_limit_eps/test_event_processing.py
  tests/reliability/agent_connection/test_keep_alive.py
Labels: hacktoberfest-accepted, pull-request/production

#3478 Add stress results comparator tool
  CHANGELOG.md
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/scripts/stress_results_comparator.py
  requirements.txt
Labels: hacktoberfest-accepted, pull-request/production

#3419 Add new `analysisd` test suite: `test_limit_eps`
  CHANGELOG.md
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/data/all_disabled_ossec.conf
  deps/wazuh_testing/wazuh_testing/modules/analysisd/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  deps/wazuh_testing/wazuh_testing/scripts/simulate_agents.py
  deps/wazuh_testing/wazuh_testing/scripts/syslog_simulator.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/run_simulator.py
  requirements.txt
  tests/integration/conftest.py
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/basic_test_module/configuration_disabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/basic_test_module/configuration_enabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_accepted_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_invalid_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/configuration_test_module/configuration_missing_configuration.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_drop_events_when_queue_is_full.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_processing_events_in_order_multi_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_processing_events_in_order_single_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/event_processing_test_module/configuration_queueing_events_after_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/basic_test_module/cases_disabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/basic_test_module/cases_enabled.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_accepted_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_invalid_values.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/configuration_test_module/cases_missing_configuration.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_drop_events_when_queue_is_full.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_processing_events_in_order_multi_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_processing_events_in_order_single_thread.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/event_processing_test_module/cases_queueing_events_after_limitation.yaml
  tests/integration/test_analysisd/test_limit_eps/test_basic.py
  tests/integration/test_analysisd/test_limit_eps/test_configuration.py
  tests/integration/test_analysisd/test_limit_eps/test_event_processing.py
  tests/reliability/agent_connection/test_keep_alive.py
Labels: hacktoberfest-accepted, pull-request/production

#3484 Refactor test only future events
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/logcollector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/logcollector/event_monitor.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  tests/integration/test_logcollector/test_only_future_events/data/configuration_template/configuration_only_future_events.yaml
  tests/integration/test_logcollector/test_only_future_events/data/test_cases/cases_only_future_events.yaml
  tests/integration/test_logcollector/test_only_future_events/test_only_future_events.py
Labels: type/test-development, target/4.4.0, subteam/qa-main, pull-request/production

#3271 Fix tests fails caused by stats socket changes
  .github/workflows/scripts/commits_checker.py
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/test_analysisd/test_limit_eps/test_event_processing.py
  tests/integration/test_logtest/test_configuration/test_get_configuration_sock.py
  tests/integration/test_logtest/test_log_process_options/data/rules_verbose.yaml
  tests/integration/test_remoted/test_agent_communication/test_request_agent_info.py
  tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
  tests/integration/test_wazuh_db/test_wazuhdb_getconfig.py
Labels: hacktoberfest-accepted, pull-request/production

#3381 FIM IT: Fix file_limit and registry_limit test suites
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/fim_module/__init__.py
  deps/wazuh_testing/wazuh_testing/fim_module/event_monitor.py
  deps/wazuh_testing/wazuh_testing/fim_module/fim_variables.py
  deps/wazuh_testing/wazuh_testing/modules/fim/__init__.py
  tests/integration/test_fim/conftest.py
  tests/integration/test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py
  tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_entries_match_path_count.py
  tests/integration/test_fim/test_files/test_file_limit/data/wazuh_conf.yaml
  tests/integration/test_fim/test_files/test_file_limit/data/wazuh_conf_delete_full.yaml
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_capacity_alerts.py
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_default.py
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_delete_full.py
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_full.py
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_no_limit.py
  tests/integration/test_fim/test_files/test_file_limit/test_file_limit_values.py
  tests/integration/test_fim/test_files/test_max_eps/test_max_eps.py
  tests/integration/test_fim/test_registry/test_registry_limit/data/wazuh_conf.yaml
  tests/integration/test_fim/test_registry/test_registry_limit/test_registry_key_limit_full.py
  tests/integration/test_fim/test_registry/test_registry_limit/test_registry_key_limit_values.py
  tests/integration/test_fim/test_registry/test_registry_limit/test_registry_limit_capacity_alerts.py
  tests/integration/test_fim/test_registry/test_registry_limit/test_registry_limit_values.py
  tests/integration/test_fim/test_registry/test_registry_limit/test_registry_value_limit_full.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_disk_quota/test_registry_disk_quota_bigger_file_limit.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_disk_quota/test_registry_disk_quota_values.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_all_limits_disabled.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_diff_size_limit_values.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_file_size_values.py
  tests/integration/test_fim/test_synchronization/test_registry_responses_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_disabled_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_registry_enabled_win32.py
Labels: pull-request/development

#3509 Add new logging tests for analysisd EPS limitation
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  tests/integration/test_analysisd/test_limit_eps/data/configuration_template/logging_test_module/configuration_dropping_events.yaml
  tests/integration/test_analysisd/test_limit_eps/data/test_cases/logging_test_module/cases_dropping_events.yaml
  tests/integration/test_analysisd/test_limit_eps/test_logging.py
Labels: hacktoberfest-accepted, pull-request/production

#3499 Refactor integratord `test_integratord_read_json_file_deleted`
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/analysisd/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/integratord/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/conftest.py
  tests/integration/test_integratord/conftest.py
  tests/integration/test_integratord/data/configuration_template/config_integratord_read_json_alerts.yaml
  tests/integration/test_integratord/data/configuration_template/configuration_integratord_read_json_alerts.yaml
  tests/integration/test_integratord/data/test_cases/cases_integratord_change_inode_alert.yaml
  tests/integration/test_integratord/data/test_cases/cases_integratord_read_invalid_json_alerts.yaml
  tests/integration/test_integratord/data/test_cases/cases_integratord_read_json_file_deleted.yaml
  tests/integration/test_integratord/data/test_cases/cases_integratord_read_valid_json_alerts.yaml
  tests/integration/test_integratord/test_integratord_change_inode_alert.py
  tests/integration/test_integratord/test_integratord_read_json_alerts.py
  tests/integration/test_integratord/test_integratord_read_json_file_deleted.py
Labels: pull-request/production

#3516 Add wazuh docker tool for auto-deploying `wazuh-manager` or `wazuh-agent`
  tools/wazuh_docker/Dockerfile
  tools/wazuh_docker/entrypoint.py
  tools/wazuh_docker/readme.md
Labels: hacktoberfest-accepted
