Repository wazuh/wazuh-qa, pull requests merged in 2022-02, with the labels that each got.

#2417 IT Tests: FIM - Refactor limits test of test report changes
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/fim.py
  deps/wazuh_testing/wazuh_testing/fim_module/fim_synchronization.py
  deps/wazuh_testing/wazuh_testing/fim_module/fim_variables.py
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/wazuh_variables.py
  tests/integration/test_fim/test_files/test_report_changes/data/wazuh_conf.yaml
  tests/integration/test_fim/test_files/test_report_changes/data/wazuh_conf_diff.yaml
  tests/integration/test_fim/test_files/test_report_changes/test_diff_size_limit_configured.py
  tests/integration/test_fim/test_files/test_report_changes/test_diff_size_limit_default.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_file_size_default.py
  tests/integration/test_fim/test_synchronization/test_sync_disabled_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_registry_disabled_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_registry_enabled_win32.py
Labels: subteam/qa-storm

#2535 IT Test: Module (FIM) - Replace callback_generator to generate_monitoring_callback
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/fim_module/fim_synchronization.py
  tests/integration/test_fim/test_files/test_report_changes/test_diff_size_limit_configured.py
  tests/integration/test_fim/test_files/test_report_changes/test_diff_size_limit_default.py
  tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_file_size_default.py
  tests/integration/test_fim/test_synchronization/test_sync_disabled_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_registry_disabled_win32.py
  tests/integration/test_fim/test_synchronization/test_sync_registry_enabled_win32.py
Labels: subteam/qa-storm

#2538 Vulnerability detector test module refactor: `test_providers_multiple_providers`
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  tests/integration/test_vulnerability_detector/test_providers/data/configuration_template/providers_multiple_feeds_provider.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/test_multiple_feeds_provider.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/wazuh_providers_multiple_providers.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_feeds_provider.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_providers.py
Labels: subteam/qa-thunder

#2540 Vulnerability detector test module refactor: `test_min_full_scan_interval`
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/test_general_settings/data/configuration_template/min_full_scan_interval.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/data/test_cases/test_min_full_scan_interval.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_min_full_scan_interval.py
Labels: subteam/qa-thunder

#2550 Vulnerability detector test module refactor: test_general_settings_retry_interval
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/global_db.py
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/utils.py
  tests/integration/conftest.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_extra_tags_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_invalid_syntax_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_invalid_values_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_missing_tags_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_extra_tags_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_invalid_syntax_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_invalid_values_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_missing_tags_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_extra_tags_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_invalid_syntax_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_invalid_values_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_missing_tags_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_extra_fields_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_invalid_syntax_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_invalid_values_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_missing_fields_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_extra_fields_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_invalid_syntax_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_invalid_values_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_missing_fields_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_custom_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_url_feeds.py
  tests/integration/test_vulnerability_detector/test_general_settings/data/configuration_template/retry_interval.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/data/test_cases/test_retry_interval.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_retry_interval.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_vd_retry_interval.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_update_from_year.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_alert_vulnerability_removal.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_redhat_duplicate_vulns.py
  tests/integration/test_vulnerability_detector/test_scan_types/test_baseline_scan_type.py
  tests/integration/test_vulnerability_detector/test_scan_types/test_full_scan_type.py
  tests/integration/test_vulnerability_detector/test_scan_types/test_partial_scan_type.py
Labels: subteam/qa-thunder

#2553 Vulnerability detector test module refactor: `test_providers_update_from_year`
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/test_vulnerability_detector/test_providers/data/configuration_template/providers_update_from_year.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/test_providers_update_from_year.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_providers_update_from_year.py
Labels: subteam/qa-thunder

#2547 Vulnerability detector test module refactor: `test_providers_no_os`
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_vulnerability_detector/test_providers/data/configuration_template/providers_no_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/test_no_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_providers_no_os.py
Labels: subteam/qa-thunder

#2541 Fix Wazuh DB tests and disable `test_syscollector_events`
  deps/wazuh_testing/wazuh_testing/db_interface/__init__.py
  tests/integration/conftest.py
  tests/integration/test_analysisd/conftest.py
  tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: subteam/qa-thunder

#2549 Vulnerability detector test module refactor: `test_providers_os`
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_vulnerability_detector/test_providers/data/configuration_template/providers_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/test_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/wazuh_providers_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_providers_os.py
Labels: subteam/qa-thunder

#2308 IPv6 system tests: `agent-auth`
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/system.py
  tests/system/provisioning/basic_environment/README.md
  tests/system/provisioning/basic_environment/ansible.cfg
  tests/system/provisioning/basic_environment/destroy.yml
  tests/system/provisioning/basic_environment/inventory.yml
  tests/system/provisioning/basic_environment/playbook.yml
  tests/system/provisioning/basic_environment/roles/agent-role/files/ossec.conf
  tests/system/provisioning/basic_environment/roles/agent-role/tasks/main.yml
  tests/system/provisioning/basic_environment/roles/manager-role/files/ossec.conf
  tests/system/provisioning/basic_environment/roles/manager-role/tasks/main.yml
  tests/system/provisioning/basic_environment/vars/configurations.yml
  tests/system/provisioning/basic_environment/vars/main.yml
  tests/system/test_agent_auth/data/config.yml
  tests/system/test_agent_auth/data/messages.yml
  tests/system/test_agent_auth/data/test_agent_auth_cases.yml
  tests/system/test_agent_auth/test_agent_auth.py
  tests/system/test_enrollment/data/config.yml
  tests/system/test_enrollment/data/messages.yml
  tests/system/test_enrollment/data/test_enrollment_cases.yml
  tests/system/test_enrollment/test_enrollment.py
Labels: subteam/qa-hurricane

#2443 System Tests: FIM - Synchronization process
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/system.py
  tests/system/README.md
  tests/system/provisioning/one_manager_agent/ansible.cfg
  tests/system/provisioning/one_manager_agent/destroy.yml
  tests/system/provisioning/one_manager_agent/inventory.yml
  tests/system/provisioning/one_manager_agent/playbook.yml
  tests/system/provisioning/one_manager_agent/roles/agent-role/files/ossec.conf
  tests/system/provisioning/one_manager_agent/roles/agent-role/tasks/main.yml
  tests/system/provisioning/one_manager_agent/roles/manager-role/files/ossec.conf
  tests/system/provisioning/one_manager_agent/roles/manager-role/tasks/main.yml
  tests/system/provisioning/one_manager_agent/vars/configurations.yml
  tests/system/provisioning/one_manager_agent/vars/main.yml
  tests/system/test_fim/__init__.py
  tests/system/test_fim/test_files/__init__.py
  tests/system/test_fim/test_files/data/delete_message.yml
  tests/system/test_fim/test_files/data/messages.yml
  tests/system/test_fim/test_files/data/wait_fim_scan.yml
  tests/system/test_fim/test_files/test_files_cud.py
Labels: subteam/qa-storm

#2575 Vulnerability detector test module refactor: `test_duplicate_feeds`
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_missing_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_multiple_provider_feeds.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_from_year.py
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration/wazuh_redhat_duplicate_vulns.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_alert_vulnerability_removal.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_redhat_duplicate_vulns.py
Labels: subteam/qa-thunder

#2564 Remoted IT - Fix imports, fixtures and warnings
  deps/wazuh_testing/wazuh_testing/remote.py
  tests/integration/test_remoted/conftest.py
  tests/integration/test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_too_big.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py
Labels: subteam/qa-hurricane

#2557 Change callback function used for system tests
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
Labels: subteam/qa-hurricane

#2536 System Tests: Module (FIM) - FIM Files Events: System test for FIM synchronization process
  CHANGELOG.md
  tests/system/provisioning/one_manager_agent/roles/agent-role/files/ossec.conf
  tests/system/provisioning/one_manager_agent/roles/manager-role/tasks/main.yml
  tests/system/scripts/system_query_db.py
  tests/system/test_fim/__init__.py
  tests/system/test_fim/test_files/test_files_cud.py
  tests/system/test_fim/test_synchronization/__init__.py
  tests/system/test_fim/test_synchronization/data/agent_initializing_synchronization.yml
  tests/system/test_fim/test_synchronization/data/delete_message.yml
  tests/system/test_fim/test_synchronization/data/manager_initializing_synchronization.yml
  tests/system/test_fim/test_synchronization/data/messages.yml
  tests/system/test_fim/test_synchronization/data/wait_fim_scan.yml
  tests/system/test_fim/test_synchronization/test_synchronization.py
Labels: subteam/qa-storm

#2301 Fix logcollector skipped tests
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/conftest.py
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_dbg.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_exclude.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_only_future_events.py
  tests/integration/test_logcollector/test_location/test_location.py
  tests/integration/test_logcollector/test_location_custom_sockets/test_location_custom_sockets.py
  tests/integration/test_logcollector/test_macos/data/wazuh_macos_format_only_future_events.yaml
  tests/integration/test_logcollector/test_macos/test_macos_file_status_predicate.py
  tests/integration/test_logcollector/test_macos/test_macos_format_basic.py
  tests/integration/test_logcollector/test_macos/test_macos_format_only_future_events.py
  tests/integration/test_logcollector/test_macos/test_macos_format_query.py
  tests/integration/test_logcollector/test_macos/test_macos_log_process.py
  tests/integration/test_logcollector/test_options/test_options_state_interval.py
  tests/integration/test_logcollector/test_options/test_options_state_interval_no_file.py
  tests/integration/test_logcollector/test_reconnect_time/test_reconnect_time.py
Labels: subteam/qa-hurricane, subteam/qa-earthquake

#2319 Fix test command execution dbg for CentOS7
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_dbg.py
Labels: subteam/qa-hurricane, subteam/qa-earthquake

#2605 Adapt `qa-docs` to the new framework terminology
  deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/code_parser.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/index_data.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/pytest_wrap.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/utils.py
  deps/wazuh_testing/wazuh_testing/scripts/qa_docs.py
Labels: subteam/qa-thunder

#2602 IT 2532- Test set_agent_groups WDB command
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/test_wazuh_db/test_set_agent_groups/data/set_agent_groups.yaml
  tests/integration/test_wazuh_db/test_set_agent_groups/test_set_agent_groups.py
Labels: team/qa, test/integration, feature/wazuh-db, subteam/qa-storm
