Repository wazuh/wazuh-qa, pull requests merged in 2022-07, with the labels that each got.

#2999 Remove `integrity_sync` data in stable phase
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/performance/csv_parser.py
  tests/performance/test_cluster/test_cluster_performance/data/10w_50000a_thresholds.yaml
Labels: team/qa, subteam/qa-hurricane, qa-revision

#3062 E2E Tests: Virustotal
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/active_response_script/remove-threat.sh
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/playbooks/configuration.yaml
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/playbooks/generate_events.yaml
  tests/end_to_end/test_virustotal/test_virustotal_active_response/data/test_cases/cases_virustotal.yaml
  tests/end_to_end/test_virustotal/test_virustotal_active_response/test_virustotal_active_response.py
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/configuration.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/generate_events.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/data/test_cases/cases_virustotal.yaml
  tests/end_to_end/test_virustotal/test_virustotal_fim/test_virustotal_fim.py
Labels: team/qa, subteam/qa-hurricane

#3069 E2E test: Test the detection of a suspicious binary
  tests/end_to_end/conftest.py
  tests/end_to_end/test_detecting_suspicious_binaries/data/configuration/trojan_script.sh
  tests/end_to_end/test_detecting_suspicious_binaries/data/playbooks/configuration.yaml
  tests/end_to_end/test_detecting_suspicious_binaries/data/playbooks/generate_events.yaml
  tests/end_to_end/test_detecting_suspicious_binaries/data/playbooks/teardown_playbook.yaml
  tests/end_to_end/test_detecting_suspicious_binaries/data/test_cases/cases_detecting_suspicious_binaries.yaml
  tests/end_to_end/test_detecting_suspicious_binaries/test_detecting_suspicious_binaries.py
Labels: team/qa, subteam/qa-hurricane

#3088 Fix Remoted IT: `test_agent_communication`
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/remote.py
Labels: team/qa, subteam/qa-hurricane

#3083 Fix GCloud IT: test_max_messages error not received expected messages - 4.4
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/gcloud.py
Labels: team/qa, subteam/qa-storm

#3032 System tests: Automatic Provision - Add custom QA roles
  provisioning/playbooks/apache.yml
  provisioning/playbooks/qa_framework.yml
  provisioning/roles/apache/tasks/Linux.yml
  provisioning/roles/apache/tasks/MacOS.yml
  provisioning/roles/apache/tasks/Solaris.yml
  provisioning/roles/apache/tasks/Windows.yml
  provisioning/roles/apache/tasks/main.yml
  provisioning/roles/apache/vars/Debian.yml
  provisioning/roles/apache/vars/MacOS.yml
  provisioning/roles/apache/vars/RedHat.yml
  provisioning/roles/apache/vars/Solaris.yml
  provisioning/roles/apache/vars/Windows.yml
  provisioning/roles/apache/vars/main.yml
  provisioning/roles/qa_framework/defaults/main.yml
  provisioning/roles/qa_framework/tasks/Solaris.yml
  provisioning/roles/qa_framework/tasks/Unix.yml
  provisioning/roles/qa_framework/tasks/Windows.yml
  provisioning/roles/qa_framework/tasks/main.yml
  provisioning/roles/qa_framework/vars/Solaris.yml
  provisioning/roles/qa_framework/vars/Unix.yml
  provisioning/roles/qa_framework/vars/Windows.yml
  provisioning/roles/qa_framework/vars/macOS.yml
  provisioning/roles/qa_framework/vars/main.yml
Labels: team/qa, subteam/qa-thunder

#3090 E2E Test: Vulnerability detector - Linux and Windows
  tests/end_to_end/test_vulnerability_detector/data/playbooks/configuration.yaml
  tests/end_to_end/test_vulnerability_detector/data/playbooks/generate_events.yaml
  tests/end_to_end/test_vulnerability_detector/data/playbooks/teardown.yaml
  tests/end_to_end/test_vulnerability_detector/data/test_cases/cases_vulnerability_detector.yaml
  tests/end_to_end/test_vulnerability_detector/test_vulnerability_detector.py
Labels: team/qa, subteam/qa-hurricane

#3111 Add 'force reconnect' feature to agent_simulator
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
Labels: team/qa, type/enhancement, tool/agent-simulator, subteam/qa-hurricane, qa-revision

#3110 Fix Analysisd IT: test_syscollector_events failure on wait_for_analysisd_startup - 4.4
  CHANGELOG.md
  tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
Labels: team/qa, subteam/qa-storm

#3131 E2E tests: Add new test for FIM events
  tests/end_to_end/test_fim/data/playbooks/configuration.yaml
  tests/end_to_end/test_fim/data/playbooks/generate_events.yaml
  tests/end_to_end/test_fim/data/playbooks/teardown.yaml
  tests/end_to_end/test_fim/data/test_cases/cases_fim.yaml
  tests/end_to_end/test_fim/test_fim.py
Labels: team/qa, subteam/qa-hurricane
