Repository wazuh/wazuh-qa, pull requests merged in 2022-01, with the labels that each got.

#2351 Fixed a flaw regarding chmod
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2360 Fixed a flaw regarding subprocess calls
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2359 Mark API flaws as false positive
  tests/scans/code_analysis/known_flaws/known_flaws_api.json
Labels: subteam/qa-hurricane

#2338 Mark use of MD5 in Azure integration as false positive
  tests/scans/code_analysis/known_flaws/known_flaws_wodles.json
Labels: subteam/qa-hurricane

#2350 Fixed a flaw regarding temp folders
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2384 Move flaw regarding use of MD5 functions to false positives
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2415 IT Solaris Jenkins: Fix requirements
  requirements.txt
Labels: subteam/qa-hurricane

#2392 Make `simulate-api-load` CLI run tasks simultaneously
  deps/wazuh_testing/wazuh_testing/scripts/simulate_api_load.py
Labels: subteam/qa-hurricane

#2380 Remove deprecated configurations
  tests/system/provisioning/agentless_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/agentless_cluster/roles/worker-role/files/ossec.conf
  tests/system/provisioning/basic_cluster/roles/agent-role/files/ossec.conf
  tests/system/provisioning/basic_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/basic_cluster/roles/worker-role/files/ossec.conf
  tests/system/provisioning/enrollment_cluster/roles/agent-role/files/ossec.conf
  tests/system/provisioning/enrollment_cluster/roles/master-role/files/ossec.conf
  tests/system/provisioning/enrollment_cluster/roles/worker-role/files/ossec.conf
Labels: team/framework, subteam/qa-hurricane

#2370 Update API configuration integration tests
  deps/wazuh_testing/wazuh_testing/api.py
  tests/integration/test_api/conftest.py
  tests/integration/test_api/test_config/test_https/data/conf.yaml
  tests/integration/test_api/test_config/test_https/test_https.py
  tests/integration/test_api/test_config/test_logs/data/conf.yaml
  tests/integration/test_api/test_config/test_logs/test_logs.py
Labels: subteam/qa-hurricane

#2400 WazuhDB IT: Fix for 4.3
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
  tests/integration/test_wazuh_db/data/agent/fim_messages.yaml
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: subteam/qa-thunder, subteam/qa-hurricane

#2407 Migrate test_cpe_indexing documentation to qa-docs
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_vulnerability_detector/test_windows/test_cpe_indexing.py
Labels: subteam/qa-thunder

#2346 Migrate test_wazuh_db documentation to qa-docs
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: subteam/qa-thunder

#2357 Migrate test_feeds documentation to qa-docs
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_extra_tags_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_invalid_syntax_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_invalid_values_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/alas/test_missing_tags_alas_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_extra_tags_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_invalid_syntax_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_invalid_values_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/canonical/test_missing_tags_canonical_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_extra_tags_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_invalid_syntax_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_invalid_values_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/debian/test_missing_tags_debian_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_extra_fields_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_invalid_syntax_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_invalid_values_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/msu/test_missing_fields_msu_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_extra_fields_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_invalid_syntax_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_invalid_values_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/redhat/test_missing_fields_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_custom_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_url_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
Labels: subteam/qa-thunder

#2398 Migrate test_scan_results documentation to qa-docs
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_alas_inventory_alas_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_archliux_inventory_archlinux_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_debian_inventory_debian_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_macos_inventory.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_msu_inventory_msu_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_redhat_duplicate_vulns.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_redhat_inventory_redhat_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_different_cves.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_providers_and_nvd_feed.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_ubuntu_inventory_canonical_feed.py
Labels: subteam/qa-thunder

#2387 Migrate test_general_setting documentation to qa-docs
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_enabled.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_ignore_time.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_interval.py
  tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_run_on_start.py
Labels: subteam/qa-thunder

#2377 Migrate test_providers documentation to qa-docs
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_providers_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_providers.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_no_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_update_from_year.py
  tests/integration/test_vulnerability_detector/test_providers/test_providers_update_interval.py
Labels: subteam/qa-thunder

#2422 Migrate `test_rids` documentation to `qa-docs`
  tests/integration/test_rids/test_rids.py
  tests/integration/test_rids/test_rids_conf.py
Labels: subteam/qa-thunder

#2431 Add the warning list for `check_file_system_integrity` test
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
  tests/check_file_system_integrity/data/warning_list.txt
  tests/check_file_system_integrity/launcher.py
  tests/check_file_system_integrity/test_check_file_system_integrity.py
Labels: type/research, subteam/qa-thunder, test/check-files

#2348 ManInTheMiddle IPV6 support
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
Labels: subteam/qa-hurricane

#2419 Delete unnecessary `CLIENT_KEYS_PATH`
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
Labels: subteam/qa-hurricane

#2288 IPv6 - New server address configuration test
  deps/wazuh_testing/wazuh_testing/agent.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  tests/integration/test_enrollment/conftest.py
  tests/integration/test_enrollment/data/server_address_configuration.yaml
  tests/integration/test_enrollment/test_agentd_server_address_configuration.py
Labels: subteam/qa-hurricane

#2296 Improve the `agent_files_deletion` test
  tests/system/README.md
  tests/system/provisioning/basic_cluster/roles/master-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/worker-role/tasks/main.yml
  tests/system/test_cluster/test_agent_files_deletion/data/get_wdb_agent.py
  tests/system/test_cluster/test_agent_files_deletion/data/messages.yml
  tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
Labels: team/framework, feature/cluster, feature/api, subteam/qa-hurricane

#2436 Filesystem integrity test preparation
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
  tests/system/filesystem_integrity/README.md
  tests/system/filesystem_integrity/conftest.py
  tests/system/filesystem_integrity/data/warning_list.txt
  tests/system/filesystem_integrity/launcher.py
  tests/system/filesystem_integrity/test_check_file_system_integrity.py
Labels: type/feature, type/research, type/fix, subteam/qa-thunder, test/check-files

#2378 IPv6 integration tests: Remoted local IP invalid test
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_invalid.py
Labels: subteam/qa-hurricane

#2381 IPv6 integration tests: Remoted syslog allowed denied IPs valid
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py
Labels: subteam/qa-hurricane

#2402 Remove `test_basic_configuration_ipv6`
  docs/tests/integration/test_remoted/test_configuration/index.md
  docs/tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.md
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.py
Labels: subteam/qa-hurricane

#2382 IPv6 integration tests: Remoted syslog allowed IPs invalid
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_ips_invalid.py
Labels: subteam/qa-hurricane

#2386 IPv6 integration tests: Remoted syslog denied IPs invalid
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py
Labels: subteam/qa-hurricane

#2395 IPv6 integration tests: Remoted syslog denied IPs
  deps/wazuh_testing/wazuh_testing/remote.py
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py
Labels: subteam/qa-hurricane

#2349 Fixed a flaw regarding xml calls
  tests/scans/code_analysis/known_flaws/known_flaws_framework.json
Labels: subteam/qa-hurricane

#2404 Fix AR tests according to IPv6 development
  tests/integration/test_active_response/test_execd/test_execd_firewall_drop.py
  tests/integration/test_active_response/test_execd/test_execd_restart.py
Labels: subteam/qa-hurricane

#2446 Skip test_registry_file_limit_values
  CHANGELOG.md
  tests/integration/test_fim/test_registry/test_registry_file_limit/test_registry_limit_values.py
Labels: team/qa, type/bug, feature/fim, type/fix, subteam/qa-storm

#2411 Fix the `agent_info_sync` test according to new changes
  tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
  tests/system/test_cluster/test_agent_info_sync/data/messages_deletion.yml
  tests/system/test_cluster/test_agent_info_sync/data/messages_remove_agent.yml
  tests/system/test_cluster/test_agent_info_sync/test_agent_info_sync.py
  tests/system/test_cluster/utils/get_wdb_agent.py
Labels: team/framework, subteam/qa-hurricane

#2439 Remoted IPv6 tests
  deps/wazuh_testing/wazuh_testing/remote.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  docs/tests/integration/test_remoted/test_configuration/index.md
  docs/tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.md
  tests/integration/test_remoted/conftest.py
  tests/integration/test_remoted/test_agent_communication/test_request_agent_info.py
  tests/integration/test_remoted/test_agent_communication/test_shared_configuration.py
  tests/integration/test_remoted/test_configuration/data/wazuh_basic_configuration.yaml
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_connection.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_port.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_syslog.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_too_big.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_rids_closing_time_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_ips_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_no_allowed_ips.py
Labels: subteam/qa-hurricane

#2416 Fix `wazuh-metrics` CLI bug when child processes restart
  deps/wazuh_testing/wazuh_testing/scripts/wazuh_metrics.py
  deps/wazuh_testing/wazuh_testing/tools/performance/binary.py
Labels: subteam/qa-hurricane

#2300 Add test fim with file currently open
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/integration/test_fim/test_files/test_basic_usage/data/wazuh_basic_conf.yaml
  tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_currently_open.py
Labels: subteam/qa-storm

#2302 Remove deprecated test on FIM
  tests/integration/test_fim/test_files/test_benchmark/data/wazuh_conf.yaml
  tests/integration/test_fim/test_files/test_benchmark/test_benchmark.py
  tests/integration/test_fim/test_files/test_benchmark/test_report_changes_big.py
  tests/integration/test_fim/test_files/test_stats_integrity_sync/data/template_agent.conf
  tests/integration/test_fim/test_files/test_stats_integrity_sync/data/template_wazuh_conf.conf
  tests/integration/test_fim/test_files/test_stats_integrity_sync/test_FIM_performance.py
  tests/integration/test_fim/test_files/test_stats_integrity_sync/test_stats_integrity_sync.py
Labels: subteam/qa-storm

#2200 Adapt logtest ITs given the rules skipping
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/custom_rule_11.xml
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/custom_rule_8.xml
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/invalid_rules_syntax.yaml
Labels: team/qa, subteam/qa-earthquake

#2454 Fix version validation in `qa-ctl` config generator
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
Labels: subteam/qa-thunder

#2163 Migrate `test_configuration` (1/2) of `test_logcollector` documentation to `qa-docs`
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_age.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_alias.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_command.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_exclude.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_frequency.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_label.py
Labels: subteam/qa-earthquake

#2175 Migrate `test_macos` of `test_logcollector` documentation to `qa-docs`
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_logcollector/test_macos/test_macos_file_status_basic.py
  tests/integration/test_logcollector/test_macos/test_macos_file_status_predicate.py
  tests/integration/test_logcollector/test_macos/test_macos_file_status_when_no_macos.py
  tests/integration/test_logcollector/test_macos/test_macos_format_basic.py
  tests/integration/test_logcollector/test_macos/test_macos_format_only_future_events.py
  tests/integration/test_logcollector/test_macos/test_macos_format_query.py
  tests/integration/test_logcollector/test_macos/test_macos_log_process.py
  tests/integration/test_logcollector/test_macos/test_macos_multiline_values.py
Labels: subteam/qa-earthquake

#2180 Migrate several test groups of `test_logcollector` documentation to `qa-docs`
  deps/wazuh_testing/wazuh_testing/qa_docs/schema.yaml
  tests/integration/test_logcollector/test_location/test_location.py
  tests/integration/test_logcollector/test_location/test_location_exclude.py
  tests/integration/test_logcollector/test_location_custom_sockets/test_location_custom_sockets.py
  tests/integration/test_logcollector/test_log_format/test_log_format_values.py
  tests/integration/test_logcollector/test_only_future_events/test_only_future_events.py
  tests/integration/test_logcollector/test_options/test_options_state_interval.py
  tests/integration/test_logcollector/test_options/test_options_state_interval_no_file.py
  tests/integration/test_logcollector/test_reconnect_time/test_reconnect_time.py
  tests/integration/test_logcollector/test_statistics/test_statistics_macos.py
Labels: subteam/qa-earthquake

#2192 Implement Authd tests code improvements.
  deps/wazuh_testing/wazuh_testing/authd.py
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/test_authd/conftest.py
  tests/integration/test_authd/force_options/README.md
  tests/integration/test_authd/force_options/test_authd_force_options.py
  tests/integration/test_authd/force_options/test_authd_force_options_invalid_config.py
  tests/integration/test_authd/test_authd_key_hash.py
  tests/integration/test_authd/test_authd_local.py
Labels: feature/authd

#2409 Add wpk test documentation
  tests/integration/test_wpk/test_wpk_agent.py
  tests/integration/test_wpk/test_wpk_manager.py
  tests/integration/test_wpk/test_wpk_manager_task_states.py
Labels: subteam/qa-hurricane

#2426 Migrate test_remoted documentation to schema 2.0
  tests/integration/test_authd/test_authd_local.py
  tests/integration/test_remoted/test_active_response/test_active_response_send_ar.py
  tests/integration/test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py
  tests/integration/test_remoted/test_agent_communication/test_agents_switching_protocols.py
  tests/integration/test_remoted/test_agent_communication/test_invalid_protocol_communication.py
  tests/integration/test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py
  tests/integration/test_remoted/test_agent_communication/test_multi_agent_status.py
  tests/integration/test_remoted/test_agent_communication/test_protocols_communication.py
  tests/integration/test_remoted/test_agent_communication/test_request_agent_info.py
  tests/integration/test_remoted/test_agent_communication/test_shared_configuration.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_connection.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_port.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_connection_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_ipv6.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_syslog.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_too_big.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_rids_closing_time_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_allowed_ips_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py
  tests/integration/test_remoted/test_configuration/test_basic_configuration_syslog_no_allowed_ips.py
  tests/integration/test_remoted/test_manager_messages/test_manager_ack.py
  tests/integration/test_remoted/test_socket_communication/test_ping_pong_message.py
  tests/integration/test_remoted/test_socket_communication/test_syslog_message.py
Labels: subteam/qa-hurricane

#2406 Analysisd - add new test to check the pre-decoding stage of analysisd
  CHANGELOG.md
  tests/integration/test_analysisd/test_predecoder_stage/data/syslog_socket_input.yaml
  tests/integration/test_analysisd/test_predecoder_stage/test_predecoder_stage.py
Labels: subteam/qa-earthquake
