Repository wazuh/wazuh-qa, pull requests merged in 2022-04, with the labels that each got.

#2730 IT - Fix agentd tests
  tests/integration/test_agentd/test_agentd_multi_server.py
Labels: subteam/qa-hurricane

#2771 WazuhDB IT: Nightly report - Fix test_wazuh_db_messages_agent
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
Labels: subteam/qa-hurricane

#2477 Add integration test for Logcollector: invalid localfile configuration
  deps/wazuh_testing/wazuh_testing/logcollector.py
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/configuration.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  tests/integration/conftest.py
  tests/integration/test_logcollector/test_configuration/test_basic_configuration_location.py
  tests/integration/test_logcollector/test_localfile/data/invalid_agent_conf.yaml
  tests/integration/test_logcollector/test_localfile/data/invalid_wazuh_conf.yaml
  tests/integration/test_logcollector/test_localfile/test_invalid_agent_localfile_config.py
  tests/integration/test_logcollector/test_localfile/test_invalid_wazuh_conf.py
Labels: subteam/qa-earthquake

#2645 Cluster system tests for agent groups
  tests/reliability/test_cluster/test_cluster_logs/README.md
  tests/reliability/test_cluster/test_cluster_logs/conftest.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_logs_order/data/Agent-info_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_logs_order/data/Integrity_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/README.md
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/data/Agent-groups_send.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/data/Agent-groups_send_full.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/data/Local_agent-groups.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_sync/test_cluster_sync.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/README.md
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_recv.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_recv_full.yaml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-info_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Integrity_check.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Integrity_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py
  tests/system/README.md
  tests/system/provisioning/provisioning_data.json
  tests/system/test_cluster/test_agent_enrollment/test_agent_enrollment.py
  tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
  tests/system/test_cluster/test_agent_groups/data/add_messages.yml
  tests/system/test_cluster/test_agent_groups/data/delete_messages.yml
  tests/system/test_cluster/test_agent_groups/data/synchronization_messages.yml
  tests/system/test_cluster/test_agent_groups/test_agent_groups.py
  tests/system/test_cluster/test_agent_info_sync/test_agent_info_sync.py
  tests/system/test_cluster/test_agent_key_polling/test_agent_key_polling.py
  tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
Labels: team/qa, team/framework, subteam/qa-thunder

#2764 System Test: Module (WAZUH-DB) - Sync of agents registered on nodes after seconds
  CHANGELOG.md
  tests/system/__init__.py
  tests/system/provisioning/big_cluster_40_agents/README.md
  tests/system/provisioning/big_cluster_40_agents/ansible.cfg
  tests/system/provisioning/big_cluster_40_agents/destroy.yml
  tests/system/provisioning/big_cluster_40_agents/inventory.yml
  tests/system/provisioning/big_cluster_40_agents/playbook.yml
  tests/system/provisioning/big_cluster_40_agents/roles/agent-role/files/ossec.conf
  tests/system/provisioning/big_cluster_40_agents/roles/agent-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/roles/master-role/files/ossec.conf
  tests/system/provisioning/big_cluster_40_agents/roles/master-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/roles/worker-role/files/ossec.conf
  tests/system/provisioning/big_cluster_40_agents/roles/worker-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/vars/configurations.yml
  tests/system/provisioning/big_cluster_40_agents/vars/main.yml
  tests/system/test_cluster/test_agent_groups/test_groups_sync_time.py
Labels: test/system, feature/wazuh-db, feature/cluster

#2761 System Test: Module (WAZUH-DB) - Sync of agents registered on nodes after seconds
  CHANGELOG.md
  tests/system/__init__.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_default.py
Labels: team/qa, test/system, feature/wazuh-db, feature/cluster

#2664 System Test: Module (WAZUH-DB) - Agent never_connected connects guesses a different group by default
  .gitignore
  tests/system/__init__.py
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
Labels: team/qa, test/system, feature/wazuh-db

#2746 Add a test to check the multigroups shared file content.
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/wazuh_manager.py
  tests/integration/test_remoted/conftest.py
  tests/integration/test_remoted/test_multi_groups/data/test_cases/case_file_actions.yaml
  tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
Labels: team/qa, subteam/qa-hurricane

#2777 IT Authd/Wazuh DB: Refactor for failures caused by new development of Wazuh DB
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/api.py
  deps/wazuh_testing/wazuh_testing/scripts/add_agents_to_default_group.py
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/conftest.py
  tests/integration/test_authd/data/enroll_messages.yaml
  tests/integration/test_authd/test_authd.py
  tests/integration/test_authd/test_authd_agents_ctx.py
  tests/integration/test_authd/test_authd_key_hash.py
  tests/integration/test_authd/test_authd_local.py
  tests/integration/test_authd/test_authd_use_password.py
  tests/integration/test_authd/test_authd_use_source_ip.py
  tests/integration/test_authd/test_authd_valid_name_ip.py
  tests/integration/test_authd/test_authd_worker.py
  tests/integration/test_authd/test_remote_enrollment.py
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
  tests/integration/test_wazuh_db/data/global/global_messages.yaml
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: test/integration, feature/wazuh-db, feature/authd, type/fix

#2691 IT: Wazuh-DB: Migration of agent-group files
  CHANGELOG.md
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/api.py
  deps/wazuh_testing/wazuh_testing/scripts/add_agents_to_default_group.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/conftest.py
  tests/integration/test_authd/data/enroll_messages.yaml
  tests/integration/test_authd/test_authd.py
  tests/integration/test_authd/test_authd_agents_ctx.py
  tests/integration/test_authd/test_authd_key_hash.py
  tests/integration/test_authd/test_authd_local.py
  tests/integration/test_authd/test_authd_use_password.py
  tests/integration/test_authd/test_authd_use_source_ip.py
  tests/integration/test_authd/test_authd_valid_name_ip.py
  tests/integration/test_authd/test_authd_worker.py
  tests/integration/test_authd/test_remote_enrollment.py
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
  tests/integration/test_wazuh_db/data/global/get_groups_integrity_messages.yaml
  tests/integration/test_wazuh_db/data/global/global_messages.yaml
  tests/integration/test_wazuh_db/data/global/set_agent_groups.yaml
  tests/integration/test_wazuh_db/data/global/sync_agent_groups_get.yaml
  tests/integration/test_wazuh_db/data/global/wazuh_db_backup_command.yaml
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
  tests/integration/test_wazuh_db/data/wazuh_db_backups_conf.yaml
  tests/integration/test_wazuh_db/test_db_backup.py
  tests/integration/test_wazuh_db/test_get_groups_integrity.py
  tests/integration/test_wazuh_db/test_set_agent_groups.py
  tests/integration/test_wazuh_db/test_sync_agent_groups_get.py
  tests/integration/test_wazuh_db/test_wazuh_db.py
  tests/integration/test_wazuh_db/test_wazuhdb_getconfig.py
  tests/integration/test_wazuh_db/test_wdb_backup_configs.py
Labels: team/qa, subteam/qa-storm

#2226 Add integration tests for Authd Key Request
  deps/wazuh_testing/wazuh_testing/authd.py
  tests/integration/test_authd/conftest.py
  tests/integration/test_authd/data/key_request_worker_messages.yaml
  tests/integration/test_authd/data/test_key_request_exec_path.yaml
  tests/integration/test_authd/data/test_key_request_limits.yaml
  tests/integration/test_authd/data/test_key_request_messages.yaml
  tests/integration/test_authd/data/wazuh_authd_configuration.yaml
  tests/integration/test_authd/files/fetch_keys.py
  tests/integration/test_authd/files/fetch_keys_sleep.py
  tests/integration/test_authd/test_authd_key_request_exec_path.py
  tests/integration/test_authd/test_authd_key_request_func.py
  tests/integration/test_authd/test_authd_key_request_limits.py
  tests/integration/test_authd/test_authd_key_request_worker.py
Labels: team/qa, test/integration, subteam/qa-thunder, qa-revision

#2159 System tests to cover the Agent Key Polling port to Authd
  tests/system/test_cluster/test_agent_key_polling/data/config.yml
Labels: team/qa, team/core, test/system, feature/key-polling, subteam/qa-thunder, qa-revision

#2765 Add test for tasks order
  tests/reliability/test_cluster/test_cluster_logs/conftest.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_task_order/README.md
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_task_order/test_cluster_task_order.py
Labels: team/qa, team/framework, subteam/qa-hurricane, qa-revision

#2758 Adapting the performance and reliability tests for Python version 3.7.10
  tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_logs_order/test_cluster_logs_order.py
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_sync/test_cluster_sync.py
Labels: team/qa, team/framework, subteam/qa-hurricane, qa-revision

#2829 2825 fix multigroups
  tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
Labels: team/qa, subteam/qa-storm

#2820 IT: VDT - Add test_providers cases for SUSE Linux Enterprise
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_missing_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_from_year.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_missing_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_multiple_provider_feeds.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_from_year.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_interval.py
Labels: team/qa, subteam/qa-storm

#2833 IT: VDT - Add test_feeds cases for SUSE Linux Enterprise
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
Labels: team/qa, subteam/qa-storm
