Repository wazuh/wazuh-qa, pull requests merged in 2022-03, with the labels that each got.

#2502 Reliability test: Standardize reliability tests data sources
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/scripts/wazuh_report.py
  deps/wazuh_testing/wazuh_testing/tools/sources/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/sources/report_generator.py
Labels: subteam/qa-hurricane

#2569 Remoted Reliablility Tests: Agent connection
  tests/reliability/agent_connection/test_agent_connection.py
  tests/reliability/agent_connection/test_keep_alive.py
  tests/reliability/conftest.py
  tests/reliability/general/know_messages.json
  tests/reliability/general/test_error_messages.py
Labels: subteam/qa-hurricane

#2607 IT 2532 - Test get-groups-integrity WDB command
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/test_wazuh_db/data/global/get_groups_integrity_messages.yaml
  tests/integration/test_wazuh_db/data/global/set_agent_groups.yaml
  tests/integration/test_wazuh_db/test_get_groups_integrity.py
  tests/integration/test_wazuh_db/test_set_agent_groups.py
Labels: team/qa, feature/wazuh-db, subteam/qa-storm, type/jenkins-integration

#2610 Vulnerability detector test module refactor: `test_download_feeds`
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
Labels: subteam/qa-thunder

#2628 Vulnerability detector test module refactor: `test_validate_feed_content`
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_json_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
Labels: subteam/qa-thunder

#2627 IT - WDB - 2532- Test wazuh-DB getconfig WDB command
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
  tests/integration/test_wazuh_db/test_wazuhdb_getconfig.py
Labels: subteam/qa-storm

#2634 Add new logic to check if a downloaded feed has been recently updated in `test_downloads_feeds` module
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/time.py
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
Labels: subteam/qa-thunder

#2626 IT - WDB - 2532- Test sync_agent_groups_get WDB command
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/test_wazuh_db/data/global/sync_agent_groups_get.yaml
  tests/integration/test_wazuh_db/test_sync_agent_groups_get.py
Labels: subteam/qa-storm

#2647 Add `qa-docs` docker, copyright and readme changes after `0.1` testing
  deps/wazuh_testing/wazuh_testing/qa_docs/README.md
  deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
  deps/wazuh_testing/wazuh_testing/qa_docs/dockerfiles/entrypoint.sh
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/code_parser.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/index_data.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/pytest_wrap.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/sanity.py
  deps/wazuh_testing/wazuh_testing/qa_docs/lib/utils.py
  deps/wazuh_testing/wazuh_testing/scripts/qa_docs.py
Labels: subteam/qa-thunder

#2570 Add new data templates to Wazuh DB integration tests
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: subteam/qa-thunder

#2637 IT 2532- Test global backup WDB command and configs
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  tests/integration/conftest.py
  tests/integration/test_wazuh_db/data/global/wazuh_db_backup_command.yaml
  tests/integration/test_wazuh_db/data/wazuh_db_backups_conf.yaml
  tests/integration/test_wazuh_db/test_db_backup.py
  tests/integration/test_wazuh_db/test_wdb_backup_configs.py
Labels: feature/wazuh-db, subteam/qa-storm, type/testing-development

#2656 Prevent Analysisd from failing on missing rule dependencies - Backport to 4.3
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/custom_rule_11.xml
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/custom_rule_8.xml
  tests/integration/test_logtest/test_invalid_rule_decoders_syntax/data/invalid_rules_syntax.yaml
Labels: subteam/qa-hurricane

#2667 Increase retries number for wazuh-metrics
  deps/wazuh_testing/wazuh_testing/scripts/wazuh_metrics.py
Labels: team/framework

#2631 Update CSV Parser tool
  deps/wazuh_testing/wazuh_testing/tools/performance/csv_parser.py
  tests/performance/test_cluster/test_cluster_performance/data/10w_50000a_thresholds.yaml
  tests/performance/test_cluster/test_cluster_performance/data/25w_50000a_thresholds.yaml
Labels: team/framework

#2663 Add the column group_config_status to agent table
  deps/wazuh_testing/wazuh_testing/remote.py
  tests/integration/test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py
  tests/integration/test_remoted/test_agent_communication/test_shared_configuration.py
  tests/integration/test_wazuh_db/data/global/global_messages.yaml
Labels: feature/wazuh-db, feature/remoted

#2662 Vulnerability detector test module refactor: `test_baseline_scan_type`
  tests/integration/test_vulnerability_detector/test_scan_types/data/test_cases/cases_baseline_scan_alert.yaml
  tests/integration/test_vulnerability_detector/test_scan_types/test_baseline_scan_type.py
Labels: status/blocked-ext, subteam/qa-thunder

#2665 System Test: Module (WAZUH-DB) - Agent never_connected connects - default group
  tests/system/__init__.py
  tests/system/test_cluster/test_agent_groups/test_agent_default_group_added.py
Labels: team/qa, test/system, feature/wazuh-db

#2657 System Test: Module (WAZUH-DB) - The agent with state different than never_connected is added to a "group_test" group by API
  tests/system/__init__.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
Labels: team/qa, test/system, feature/wazuh-db

#2612 Remoted reliability tests
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/scripts/wazuh_report.py
  deps/wazuh_testing/wazuh_testing/tools/sources/__init__.py
  deps/wazuh_testing/wazuh_testing/tools/sources/report_generator.py
  tests/reliability/agent_connection/test_agent_connection.py
  tests/reliability/agent_connection/test_keep_alive.py
  tests/reliability/conftest.py
  tests/reliability/general/know_messages.json
  tests/reliability/general/test_error_messages.py
Labels: subteam/qa-hurricane

#2682 Fix Logcollector IT: test_command_execution_dbg
  tests/integration/test_logcollector/test_command_monitoring/test_command_execution_dbg.py
Labels: subteam/qa-hurricane

#2685 Fix Agentd IT: `test_agentd_multi_server`
  tests/integration/test_agentd/test_agentd_multi_server.py
Labels: subteam/qa-hurricane

#2689 Vulnerability detector test module refactor: Test scan provider and Test scan provider + NVD
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/data/feeds/debian/custom_debian_json_feed.json
  tests/integration/test_vulnerability_detector/data/feeds/debian/custom_debian_oval_feed.xml
  tests/integration/test_vulnerability_detector/data/feeds/nvd/custom_nvd_alternative_feed.json
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_providers_and_nvd.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: subteam/qa-thunder

#2653 IT Wazuh DB: Add coverage to new commands
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/services.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/conftest.py
  tests/integration/test_wazuh_db/data/global/get_groups_integrity_messages.yaml
  tests/integration/test_wazuh_db/data/global/set_agent_groups.yaml
  tests/integration/test_wazuh_db/data/global/sync_agent_groups_get.yaml
  tests/integration/test_wazuh_db/data/global/wazuh_db_backup_command.yaml
  tests/integration/test_wazuh_db/data/global/wazuhdb_getconfig.yaml
  tests/integration/test_wazuh_db/data/wazuh_db_backups_conf.yaml
  tests/integration/test_wazuh_db/test_db_backup.py
  tests/integration/test_wazuh_db/test_get_groups_integrity.py
  tests/integration/test_wazuh_db/test_set_agent_groups.py
  tests/integration/test_wazuh_db/test_sync_agent_groups_get.py
  tests/integration/test_wazuh_db/test_wazuhdb_getconfig.py
  tests/integration/test_wazuh_db/test_wdb_backup_configs.py
Labels: team/qa, test/integration, feature/wazuh-db

#2405 Analysisd - add new test to check analysisd socket properties
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/__init__.py
  tests/integration/test_analysisd/conftest.py
  tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py
Labels: subteam/qa-hurricane

#2687 Fix `test_agent_key_polling`
  tests/system/test_cluster/test_agent_key_polling/data/messages.yml
Labels: subteam/qa-hurricane

#2670 System Test: Module (WAZUH-DB) - Adds a new node to a synchronized environment
  tests/system/__init__.py
  tests/system/provisioning/four_manager_disconnected_node/README.md
  tests/system/provisioning/four_manager_disconnected_node/ansible.cfg
  tests/system/provisioning/four_manager_disconnected_node/destroy.yml
  tests/system/provisioning/four_manager_disconnected_node/inventory.yml
  tests/system/provisioning/four_manager_disconnected_node/playbook.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/agent-role/files/ossec.conf
  tests/system/provisioning/four_manager_disconnected_node/roles/agent-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/master-role/files/ossec.conf
  tests/system/provisioning/four_manager_disconnected_node/roles/master-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/worker-role/files/ossec.conf
  tests/system/provisioning/four_manager_disconnected_node/roles/worker-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/vars/configurations.yml
  tests/system/provisioning/four_manager_disconnected_node/vars/main.yml
  tests/system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py
Labels: team/qa, test/system, feature/wazuh-db

#2668 System Test: Module (WAZUH-DB) - Agent forced to change group
  tests/system/__init__.py
  tests/system/provisioning/basic_cluster/roles/agent-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/master-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/worker-role/tasks/main.yml
  tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
Labels: team/qa, test/system, feature/wazuh-db

#2678 Modify default empty value to avoid an empty severity in Vulnerability Detector
  tests/integration/test_wazuh_db/data/agent/agent_messages.yaml
Labels: test/integration, feature/vuln-detector, type/fix

#2686 System Test: Module (WAZUH-DB) -Agent registered with group Y - group data is synced in cluster
  tests/system/__init__.py
  tests/system/provisioning/enrollment_cluster/roles/worker-role/tasks/main.yml
  tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
Labels: test/system, feature/wazuh-db

#2684 Add vulnerability detector changes for `4.3.0-RC5`
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_cpe_indexing_system.yaml
  tests/integration/test_vulnerability_detector/test_scan_types/data/test_cases/cases_baseline_scan_alert.yaml
  tests/integration/test_vulnerability_detector/test_scan_types/test_baseline_scan_type.py
  tests/integration/test_vulnerability_detector/test_scan_types/test_full_scan_type.py
  tests/integration/test_vulnerability_detector/test_scan_types/test_partial_scan_type.py
Labels: subteam/qa-thunder

#2741 Add provisioning data file to launch the system tests in a Jenkins pipeline
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  tests/system/provisioning/one_manager_agent/roles/agent-role/tasks/main.yml
  tests/system/provisioning/provisioning_data.json
Labels: subteam/qa-thunder
