Repository wazuh/wazuh-qa, pull requests merged in 2022-05, with the labels that each got.

#2437 Add the filesystem integrity module and test
  deps/wazuh_testing/setup.py
  deps/wazuh_testing/wazuh_testing/data/qactl_conf_validator_schema.json
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_instance.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/__init__.py
  deps/wazuh_testing/wazuh_testing/qa_ctl/provisioning/ansible/playbook_generator.py
  deps/wazuh_testing/wazuh_testing/scripts/check_files.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  deps/wazuh_testing/wazuh_testing/tools/s3_package.py
  deps/wazuh_testing/wazuh_testing/tools/time.py
  requirements.txt
  tests/check_files/test_filesystem_integrity/README.md
  tests/check_files/test_filesystem_integrity/conftest.py
  tests/check_files/test_filesystem_integrity/data/warning_list.txt
  tests/check_files/test_filesystem_integrity/launcher.py
  tests/check_files/test_filesystem_integrity/test_check_file_system_integrity.py
Labels: team/qa, subteam/qa-thunder

#2885 Add libssl-dev dependency to system test
  tests/system/provisioning/agentless_cluster/roles/master-role/tasks/main.yml
  tests/system/provisioning/agentless_cluster/roles/worker-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/agent-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/master-role/tasks/main.yml
  tests/system/provisioning/basic_cluster/roles/worker-role/tasks/main.yml
  tests/system/provisioning/basic_environment/roles/agent-role/tasks/main.yml
  tests/system/provisioning/basic_environment/roles/manager-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/roles/agent-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/roles/master-role/tasks/main.yml
  tests/system/provisioning/big_cluster_40_agents/roles/worker-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/agent-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/master-role/tasks/main.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/worker-role/tasks/main.yml
  tests/system/provisioning/manager_agent/roles/agent-role/tasks/main.yml
  tests/system/provisioning/manager_agent/roles/manager-role/tasks/main.yml
  tests/system/provisioning/manager_agent/roles/master-role/tasks/main.yml
  tests/system/provisioning/one_manager_agent/roles/agent-role/tasks/main.yml
  tests/system/provisioning/one_manager_agent/roles/manager-role/tasks/main.yml
Labels: team/qa, subteam/qa-storm

#2865 Add test_scan_results cases for Ubuntu 22
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  tests/integration/test_vulnerability_detector/data/feeds/canonical/custom_canonical_oval_feed.xml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
Labels: team/qa, subteam/qa-storm

#2902 VDT IT - Add SUSE Linux support to test_scan_results suite
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/db_interface/agent_db.py
  deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
  tests/integration/test_vulnerability_detector/conftest.py
  tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_no_agent_data.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: team/qa, test/integration, feature/vuln-detector, subteam/qa-storm

#2868 Add test_feeds cases for Amazon Linux 2022
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
Labels: team/qa, subteam/qa-storm

#2905 Add test_scan_results cases for Amazon Linux 2022
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/mocking/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
  tests/integration/test_vulnerability_detector/data/feeds/alas/custom_alas2022_feed.json
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_vulnerability_removal.yaml
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
  tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py
Labels: team/qa, subteam/qa-storm

#2903 Add test_providers cases for Amazon Linux 2022
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml
  tests/integration/test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml
  tests/integration/test_vulnerability_detector/test_providers/test_enabled.py
  tests/integration/test_vulnerability_detector/test_providers/test_missing_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_os.py
  tests/integration/test_vulnerability_detector/test_providers/test_update_interval.py
Labels: team/qa, test/integration, feature/vuln-detector, subteam/qa-storm, qa

#2867 IT: VDT - Add test_feeds cases for Ubuntu Jammy Jellyfish
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_validate_xml_feed_content.yaml
  tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_duplicate_feeds.py
  tests/integration/test_vulnerability_detector/test_feeds/test_import_invalid_feed_type.py
  tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
Labels: feature/vuln-detector

#2782 Move the 'get_datetime_diff' function to 'wazuh-testing' utils module
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  tests/performance/test_cluster/test_cluster_performance/data/25w_50000a_thresholds.yaml
  tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py
Labels: team/qa, team/framework, type/enhancement, subteam/qa-hurricane, qa-revision
