Repository wazuh/wazuh-qa, pull requests merged in 2023-03, with the labels that each got.

#3939 Fix FIM test_audit to update to new framework
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/fim.py
  deps/wazuh_testing/wazuh_testing/modules/fim/event_monitor.py
  tests/integration/test_fim/test_files/test_audit/data/configuration_template/configuration_remove_audit.yaml
  tests/integration/test_fim/test_files/test_audit/data/test_cases/cases_remove_audit.yaml
  tests/integration/test_fim/test_files/test_audit/data/wazuh_conf.yaml
  tests/integration/test_fim/test_files/test_audit/test_remove_audit.py
Labels: pull-request/production

#3721 Add authd test to validate error when `authd.pass` is empty
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/authd/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/authd/event_monitor.py
  tests/integration/test_authd/data/configuration_template/config_authd_use_password_invalid.yaml
  tests/integration/test_authd/data/test_cases/cases_authd_use_password_invalid.yaml
  tests/integration/test_authd/test_authd_use_password_invalid.py
Labels: target/4.5.0, role/qa-binary-beats, subteam/qa-rainbow

#3796 Umbrella integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  tests/integration/test_aws/data/configuration_template/discard_regex_test_module/configuration_discard_regex.yaml
  tests/integration/test_aws/data/configuration_template/only_logs_after_test_module/bucket_configuration_with_only_logs_after.yaml
  tests/integration/test_aws/data/configuration_template/only_logs_after_test_module/bucket_configuration_without_only_logs_after.yaml
  tests/integration/test_aws/data/configuration_template/remove_from_bucket_test_module/configuration_remove_from_bucket.yaml
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_bucket_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_bucket_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_bucket_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_bucket_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_discard_regex.py
  tests/integration/test_aws/test_only_logs_after.py
  tests/integration/test_aws/test_remove_from_bucket.py
Labels: team/framework, feature/aws

#3979 Add multigroups tests cases for `test_assign_groups_guess`
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/system.py
  tests/system/__init__.py
  tests/system/provisioning/enrollment_cluster/destroy.yml
  tests/system/provisioning/enrollment_cluster/inventory.yml
  tests/system/provisioning/enrollment_cluster/playbook.yml
  tests/system/provisioning/enrollment_cluster/vars/configurations.yaml
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
Labels: pull-request/development

#3882 Parser integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  tests/integration/test_aws/conftest.py
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_bucket_and_service_missing.yaml
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_multiple_bucket_and_service_tags.yaml
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_type_missing_in_bucket.yaml
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_type_missing_in_service.yaml
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_values_in_bucket.yaml
  tests/integration/test_aws/data/configuration_template/parser_test_module/configuration_values_in_service.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_bucket_and_service_missing.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_empty_values_in_bucket.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_empty_values_in_service.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_invalid_values_in_bucket.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_invalid_values_in_service.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_multiple_bucket_and_service_tags.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_type_missing_in_bucket.yaml
  tests/integration/test_aws/data/test_cases/parser_test_module/cases_type_missing_in_service.yaml
  tests/integration/test_aws/test_parser.py
Labels: team/framework, feature/aws
