Repository wazuh/wazuh-qa, pull requests merged in 2023-02, with the labels that each got.

#2445 Add logs to html report for system tests
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/monitoring.py
  deps/wazuh_testing/wazuh_testing/tools/system.py
  tests/system/__init__.py
  tests/system/conftest.py
  tests/system/pytest.ini
  tests/system/test_cluster/conftest.py
  tests/system/test_cluster/test_agent_enrollment/test_agent_enrollment.py
  tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
  tests/system/test_cluster/test_agent_groups/test_agent_default_group_added.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_default.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_time.py
  tests/system/test_cluster/test_agent_info_sync/test_agent_info_sync.py
  tests/system/test_cluster/test_agent_key_polling/conftest.py
  tests/system/test_cluster/test_agent_key_polling/test_agent_key_polling.py
  tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
  tests/system/test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py
Labels: pull-request/development

#3889 Fix `test_agent_groups`
  CHANGELOG.md
  tests/system/README.md
  tests/system/__init__.py
  tests/system/conftest.py
  tests/system/provisioning/enrollment_cluster/roles/master-role/tasks/main.yml
  tests/system/test_cluster/test_agent_groups/data/add_messages.yml
  tests/system/test_cluster/test_agent_groups/data/synchronization_messages.yml
  tests/system/test_cluster/test_agent_groups/test_agent_default_group_added.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_default.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_time.py
Labels: pull-request/development

#3699 VPC integration tests
  deps/wazuh_testing/wazuh_testing/modules/api/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/aws/s3_utils.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  tests/integration/test_aws/conftest.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_suffix_test_module/cases_path_suffix.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/regions_test_module/cases_regions.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_discard_regex.py
  tests/integration/test_aws/test_only_logs_after.py
  tests/integration/test_aws/test_path.py
  tests/integration/test_aws/test_path_suffix.py
  tests/integration/test_aws/test_regions.py
Labels: team/framework, feature/aws

#3880 Updated database version ` test_agent_database_version` test
  CHANGELOG.md
  tests/integration/test_wazuh_db/test_agent_database_version.py
Labels: team/qa, role/qa-data-pirates, subteam/qa-rainbow

#3896 Update `test_cluster_worker_logs_order` test
  CHANGELOG.md
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/README.md
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_sync.yml
  tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py
Labels: pull-request/development

#3895 fix `test_sync_agent_groups_get` and add function to calculate hash
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/wazuh_db.py
  tests/integration/test_wazuh_db/data/global/sync_agent_groups_get.yaml
  tests/integration/test_wazuh_db/test_sync_agent_groups_get.py
Labels: pull-request/development

#3705 AWS Config integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_suffix_test_module/cases_path_suffix.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/regions_test_module/cases_regions.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_discard_regex.py
  tests/integration/test_aws/test_path.py
  tests/integration/test_aws/test_regions.py
Labels: team/framework, feature/aws

#3900 Analysisd predecoder stage test failed
  CHANGELOG.md
  tests/integration/test_analysisd/test_predecoder_stage/data/syslog_socket_input.yaml
Labels: team/qa, feature/analysisd, type/fix, qa-internal, subteam/qa-main

#3711 ALB, CLB and NLB integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  tests/integration/test_aws/conftest.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/regions_test_module/cases_regions.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_regions.py
  tests/integration/test_aws/test_remove_from_bucket.py
Labels: team/framework, feature/aws

#3901 Improve `test_assign_groups_guess`
  CHANGELOG.md
  tests/system/provisioning/enrollment_cluster/playbook.yml
  tests/system/provisioning/enrollment_cluster/roles/agent-role/tasks/main.yaml
  tests/system/provisioning/enrollment_cluster/roles/master-role/tasks/main.yaml
  tests/system/provisioning/enrollment_cluster/roles/worker-role/tasks/main.yaml
  tests/system/provisioning/enrollment_cluster/vars/configurations.yaml
  tests/system/provisioning/enrollment_cluster/vars/configurations.yml
  tests/system/provisioning/enrollment_cluster/vars/main.yaml
  tests/system/provisioning/enrollment_cluster/vars/main.yml
  tests/system/test_cluster/test_agent_groups/data/guess_group_messages_master.yaml
  tests/system/test_cluster/test_agent_groups/data/guess_group_messages_worker.yaml
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
Labels: pull-request/development

#3715 KMS integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/aws/s3_utils.py
  deps/wazuh_testing/wazuh_testing/tools/utils.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_only_logs_after.py
Labels: team/framework, feature/aws

#3920 Fix `test_set_agent_groups`
  .github/workflows/scripts/config/yaml_linter_config.yaml
  CHANGELOG.md
  tests/integration/test_wazuh_db/data/global/set_agent_groups.yaml
  tests/integration/test_wazuh_db/test_set_agent_groups.py
Labels: pull-request/development

#3926 Fix wazuh-db integration tests for agent-groups
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/tools/wazuh_manager.py
  tests/integration/test_wazuh_db/conftest.py
  tests/integration/test_wazuh_db/data/global/get_groups_integrity_messages.yaml
  tests/integration/test_wazuh_db/data/global/set_agent_groups.yaml
  tests/integration/test_wazuh_db/data/global/sync_agent_groups_get.yaml
  tests/integration/test_wazuh_db/test_agent_database_version.py
  tests/integration/test_wazuh_db/test_get_groups_integrity.py
  tests/integration/test_wazuh_db/test_set_agent_groups.py
  tests/integration/test_wazuh_db/test_sync_agent_groups_get.py
  tests/integration/test_wazuh_db/test_wazuh_db.py
Labels: pull-request/development

#3750 Fix WazuhQAEnvironment Solaris agent provision
  CHANGELOG.md
  provisioning/roles/wazuh_environment/schema.j2
Labels: team/qa, pull-request/production

#3734 Macie integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
Labels: team/framework, feature/aws

#3736 Trusted Advisor integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_discard_regex.py
Labels: team/framework, feature/aws

#3961 Include markers for each system test environment
  CHANGELOG.md
  tests/system/pytest.ini
  tests/system/test_active_response_log_format/test_active_response_log_format.py
  tests/system/test_cluster/test_agent_enrollment/test_agent_enrollment.py
  tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
  tests/system/test_cluster/test_agent_groups/test_agent_default_group_added.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
  tests/system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
  tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py
  tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_default.py
  tests/system/test_cluster/test_agent_groups/test_groups_sync_time.py
  tests/system/test_cluster/test_agent_info_sync/test_agent_info_sync.py
  tests/system/test_cluster/test_agent_key_polling/test_agent_key_polling.py
  tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
  tests/system/test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py
  tests/system/test_fim/test_synchronization/test_synchronization.py
  tests/system/test_jwt_invalidation/test_change_rbac_mode.py
  tests/system/test_jwt_invalidation/test_change_security_resources.py
  tests/system/test_jwt_invalidation/test_disconnected_nodes.py
  tests/system/test_jwt_invalidation/test_revoke_endpoint.py
  tests/system/test_jwt_invalidation/test_update_password.py
  tests/system/test_multigroups/test_multigroups.py
Labels: team/qa, subteam/qa-main

#3971 Improve `test_agent_groups_new_cluster_node`
  CHANGELOG.md
  tests/system/provisioning/four_manager_disconnected_node/README.md
  tests/system/provisioning/four_manager_disconnected_node/destroy.yml
  tests/system/provisioning/four_manager_disconnected_node/inventory.yml
  tests/system/provisioning/four_manager_disconnected_node/playbook.yml
  tests/system/provisioning/four_manager_disconnected_node/roles/agent-role/tasks/main.yaml
  tests/system/provisioning/four_manager_disconnected_node/roles/master-role/tasks/main.yaml
  tests/system/provisioning/four_manager_disconnected_node/roles/worker-role/tasks/main.yaml
  tests/system/provisioning/four_manager_disconnected_node/vars/configurations.yaml
  tests/system/provisioning/four_manager_disconnected_node/vars/main.yaml
  tests/system/provisioning/four_manager_disconnected_node/vars/main.yml
  tests/system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py
Labels: pull-request/development

#3763 WAF integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
Labels: team/framework, feature/aws
