Repository wazuh/wazuh-qa, pull requests merged in 2023-01, with the labels that each got.

#3624 Cloudtrail integration tests
  deps/wazuh_testing/wazuh_testing/modules/aws/cli_utils.py
  deps/wazuh_testing/wazuh_testing/modules/aws/constants.py
  deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
  deps/wazuh_testing/wazuh_testing/modules/aws/db_utils.py
  deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/aws/s3_utils.py
  requirements.txt
  tests/integration/test_aws/conftest.py
  tests/integration/test_aws/data/configuration_template/basic_test_module/configuration_defaults.yaml
  tests/integration/test_aws/data/configuration_template/discard_regex_test_module/configuration_discard_regex.yaml
  tests/integration/test_aws/data/configuration_template/only_logs_after_test_module/configuration_with_only_logs_after.yaml
  tests/integration/test_aws/data/configuration_template/only_logs_after_test_module/configuration_without_only_logs_after.yaml
  tests/integration/test_aws/data/configuration_template/path_suffix_test_module/configuration_path_suffix.yaml
  tests/integration/test_aws/data/configuration_template/path_test_module/configuration_path.yaml
  tests/integration/test_aws/data/configuration_template/regions_test_module/configuration_regions.yaml
  tests/integration/test_aws/data/configuration_template/remove_from_bucket_test_module/configuration_remove_from_bucket.yaml
  tests/integration/test_aws/data/test_cases/basic_test_module/cases_defaults.yaml
  tests/integration/test_aws/data/test_cases/discard_regex_test_module/cases_discard_regex.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_multiple_calls.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_with_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/only_logs_after_test_module/cases_without_only_logs_after.yaml
  tests/integration/test_aws/data/test_cases/path_suffix_test_module/cases_path_suffix.yaml
  tests/integration/test_aws/data/test_cases/path_test_module/cases_path.yaml
  tests/integration/test_aws/data/test_cases/regions_test_module/cases_regions.yaml
  tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_from_bucket.yaml
  tests/integration/test_aws/test_basic.py
  tests/integration/test_aws/test_discard_regex.py
  tests/integration/test_aws/test_only_logs_after.py
  tests/integration/test_aws/test_path.py
  tests/integration/test_aws/test_path_suffix.py
  tests/integration/test_aws/test_regions.py
  tests/integration/test_aws/test_remove_from_bucket.py
Labels: team/framework, feature/aws

#3746 Update the Authd response when a multigroup is too long
  CHANGELOG.md
  tests/integration/test_authd/data/enroll_messages.yaml
Labels: test/integration, feature/authd

#3582 Add logcollector ignore and restrict IT tests
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/logcollector/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/logcollector/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_logcollector/test_log_filter_options/data/configuration_template/configuration_ignore_multiple_regex.yaml
  tests/integration/test_logcollector/test_log_filter_options/data/configuration_template/configuration_restrict_ignore_regex_values.yaml
  tests/integration/test_logcollector/test_log_filter_options/data/configuration_template/configuration_restrict_multiple_regex.yaml
  tests/integration/test_logcollector/test_log_filter_options/data/test_cases/cases_ignore_multiple_regex.yaml
  tests/integration/test_logcollector/test_log_filter_options/data/test_cases/cases_restrict_ignore_regex_values.yaml
  tests/integration/test_logcollector/test_log_filter_options/data/test_cases/cases_restrict_multiple_regex.yaml
  tests/integration/test_logcollector/test_log_filter_options/test_ignore_regex.py
  tests/integration/test_logcollector/test_log_filter_options/test_restrict_ignore_regex.py
  tests/integration/test_logcollector/test_log_filter_options/test_restrict_regex.py
  tests/integration/test_logcollector/test_only_future_events/test_only_future_events.py
  tests/integration/test_logcollector/test_options/data/configuration/wazuh_configuration.yaml
  tests/integration/test_logcollector/test_options/data/configuration_template/wazuh_configuration.yaml
  tests/integration/test_logcollector/test_options/test_options_state_interval.py
  tests/integration/test_logcollector/test_options/test_options_state_interval_no_file.py
Labels: pull-request/production

#3769 Vulnerability detector NVE test feed download fix
  CHANGELOG.md
  tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml
Labels: qa-internal, pull-request/production

#3669 Add win support to test_report_changes_and_diff.py
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/fim/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/fim/utils.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/integration/test_fim/conftest.py
  tests/integration/test_fim/test_files/test_report_changes/test_report_changes_and_diff.py
Labels: pull-request/production

#3768 Add a test to check the version of the agent database
  CHANGELOG.md
  tests/integration/test_wazuh_db/test_agent_database_version.py
Labels: team/qa, subteam/qa-main, pull-request/development

#3649 Add invalid/null if_sid test support
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/analysisd/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/analysisd/event_monitor.py
  tests/integration/conftest.py
  tests/integration/test_analysisd/conftest.py
  tests/integration/test_analysisd/test_signature_id/data/configuration_template/configuration_signature_id_values.yaml
  tests/integration/test_analysisd/test_signature_id/data/rules_samples/empty_signature_id_rules.xml
  tests/integration/test_analysisd/test_signature_id/data/rules_samples/invalid_signature_id_rules.xml
  tests/integration/test_analysisd/test_signature_id/data/rules_samples/null_signature_id_rules.xml
  tests/integration/test_analysisd/test_signature_id/data/rules_samples/valid_signature_id_rules.xml
  tests/integration/test_analysisd/test_signature_id/data/test_cases/cases_invalid_signature_id.yaml
  tests/integration/test_analysisd/test_signature_id/data/test_cases/cases_null_signature_id.yaml
  tests/integration/test_analysisd/test_signature_id/data/test_cases/cases_valid_signature_id.yaml
  tests/integration/test_analysisd/test_signature_id/test_signature_id.py
  tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
Labels: pull-request/production

#3565 Adapt to `multi_groups` modifications
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/remote.py
  tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
Labels: role/qa-binary-beats, subteam/qa-rainbow, pull-request/production

#3787 Add test to check netsh active response alert when firewall is disabled in Windows
  CHANGELOG.md
  tests/system/test_active_response/conftest.py
  tests/system/test_active_response/data/ansible_roles/manage_alerts/tasks/get_alert_json.yaml
  tests/system/test_active_response/data/ansible_roles/manage_alerts/tasks/search_alert.yaml
  tests/system/test_active_response/data/ansible_roles/manage_alerts/tasks/truncate_alert_json.yaml
  tests/system/test_active_response/data/ansible_roles/manage_logs/tasks/get_log_file.yaml
  tests/system/test_active_response/data/ansible_roles/manage_wazuh/tasks/restart_wazuh.yaml
  tests/system/test_active_response/data/ansible_roles/manage_wazuh_configurations/tasks/write_wazuh_config.yaml
  tests/system/test_active_response/data/ansible_roles/manage_wazuh_configurations/tasks/write_wazuh_internal_options.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_alerts/data/playbooks/configuration.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_alerts/data/playbooks/generate_events.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_alerts/data/playbooks/teardown.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_alerts/data/test_cases/cases_firewall_alerts.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_alerts/test_firewall_alerts.py
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_status/data/playbooks/configuration.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_status/data/playbooks/generate_events.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_status/data/playbooks/teardown.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_status/data/test_cases/cases_firewall_status.yaml
  tests/system/test_active_response/test_netsh_windows_command/test_firewall_status/test_firewall_status.py
Labels: pull-request/production

#3627 Add support for Whodata Windows Audit Policy Change detection
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/fim/__init__.py
  deps/wazuh_testing/wazuh_testing/modules/fim/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/fim/utils.py
  deps/wazuh_testing/wazuh_testing/tools/file.py
  tests/integration/test_fim/conftest.py
  tests/integration/test_fim/test_files/test_report_changes/test_report_changes_and_diff.py
  tests/integration/test_fim/test_files/test_whodata_policy_change/data/configuration_template/configuration_whodata_policy_change.yaml
  tests/integration/test_fim/test_files/test_whodata_policy_change/data/policy_disable.csv
  tests/integration/test_fim/test_files/test_whodata_policy_change/data/policy_enable.csv
  tests/integration/test_fim/test_files/test_whodata_policy_change/data/policy_success_removed.csv
  tests/integration/test_fim/test_files/test_whodata_policy_change/data/test_cases/cases_whodata_policy_change.yaml
  tests/integration/test_fim/test_files/test_whodata_policy_change/test_whodata_policy_change.py
Labels: pull-request/production

#3802 wazuh-db integration tests fixed on Ubuntu
  CHANGELOG.md
  tests/integration/test_wazuh_db/test_db_backup.py
Labels: pull-request/production

#3707 Add agent statistics format test
  deps/wazuh_testing/wazuh_testing/api.py
  tests/integration/test_api/test_config/test_rbac/test_rbac_mode.py
  tests/integration/test_api/test_middlewares/test_response_postprocessing.py
  tests/integration/test_api/test_middlewares/test_set_secure_headers.py
  tests/integration/test_api/test_rbac/test_add_old_resource.py
  tests/integration/test_api/test_rbac/test_admin_resources.py
  tests/integration/test_api/test_rbac/test_policy_position.py
  tests/integration/test_api/test_rbac/test_remove_relationship.py
  tests/integration/test_api/test_rbac/test_remove_resource.py
  tests/integration/test_api/test_statistics/data/configuration_template/configuration_manager_statistics_format.yaml
  tests/integration/test_api/test_statistics/data/statistics_template/agent_statistics_format_test_module/wazuh-analysisd_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/agent_statistics_format_test_module/wazuh-remoted_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-analysisd_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-remoted_template.json
  tests/integration/test_api/test_statistics/data/test_cases/agent_statistics_format_test_module/cases_agent_statistics_format.yaml
  tests/integration/test_api/test_statistics/data/test_cases/manager_statistics_format_test_module/cases_manager_statistics_format.yaml
  tests/integration/test_api/test_statistics/test_statistics_format.py
Labels: team/qa, subteam/qa-main, pull-request/development

#3720 Add Windows System folders monitoring test support
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/modules/fim/classes.py
  deps/wazuh_testing/wazuh_testing/modules/fim/event_monitor.py
  deps/wazuh_testing/wazuh_testing/modules/fim/utils.py
  tests/integration/test_fim/test_files/test_env_variables/test_nodiff.py
  tests/integration/test_fim/test_files/test_report_changes/test_report_changes_and_diff.py
  tests/integration/test_fim/test_files/test_whodata_policy_change/test_whodata_policy_change.py
  tests/integration/test_fim/test_files/test_windows_system_folder_redirection/data/configuration_template/configuration_windows_system_folder_redirection.yaml
  tests/integration/test_fim/test_files/test_windows_system_folder_redirection/data/test_cases/cases_windows_system_folder_redirection.yaml
  tests/integration/test_fim/test_files/test_windows_system_folder_redirection/test_windows_system_folder_redirection.py
Labels: pull-request/production

#3813 Add statistics format test
  CHANGELOG.md
  deps/wazuh_testing/wazuh_testing/api.py
  tests/integration/test_api/test_config/test_rbac/test_rbac_mode.py
  tests/integration/test_api/test_middlewares/test_response_postprocessing.py
  tests/integration/test_api/test_middlewares/test_set_secure_headers.py
  tests/integration/test_api/test_rbac/test_add_old_resource.py
  tests/integration/test_api/test_rbac/test_admin_resources.py
  tests/integration/test_api/test_rbac/test_policy_position.py
  tests/integration/test_api/test_rbac/test_remove_relationship.py
  tests/integration/test_api/test_rbac/test_remove_resource.py
  tests/integration/test_api/test_statistics/data/configuration_template/configuration_manager_statistics_format.yaml
  tests/integration/test_api/test_statistics/data/statistics_template/agent_statistics_format_test_module/wazuh-analysisd_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/agent_statistics_format_test_module/wazuh-remoted_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-analysisd_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json
  tests/integration/test_api/test_statistics/data/statistics_template/manager_statistics_format_test_module/wazuh-remoted_template.json
  tests/integration/test_api/test_statistics/data/test_cases/agent_statistics_format_test_module/cases_agent_statistics_format.yaml
  tests/integration/test_api/test_statistics/data/test_cases/manager_statistics_format_test_module/cases_manager_statistics_format.yaml
  tests/integration/test_api/test_statistics/test_statistics_format.py
Labels: team/qa, subteam/qa-main, pull-request/development

#3784 Skip unstable FIM report changes test
  CHANGELOG.md
  tests/integration/test_fim/test_files/test_report_changes/test_large_changes.py
Labels: pull-request/production
